// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#include "../ui.h"

void ui_event_comp_PlayerKickPanel_PlayerKickButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_PlayerKickPanel = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        KickPlayerBeforeStart(e);
    }
}

// COMPONENT PlayerKickPanel

lv_obj_t * ui_PlayerKickPanel_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_PlayerKickPanel;
    cui_PlayerKickPanel = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_PlayerKickPanel, lv_pct(100));
    lv_obj_set_height(cui_PlayerKickPanel, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(cui_PlayerKickPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_PlayerKickPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_PlayerKickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_PlayerKickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_PlayerKickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_PlayerKickPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_PlayerKickLabel;
    cui_PlayerKickLabel = lv_label_create(cui_PlayerKickPanel);
    lv_obj_set_width(cui_PlayerKickLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_PlayerKickLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_PlayerKickLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_PlayerKickLabel, "PlayerName");

    lv_obj_t * cui_PlayerKickButton;
    cui_PlayerKickButton = lv_btn_create(cui_PlayerKickPanel);
    lv_obj_set_width(cui_PlayerKickButton, 25);
    lv_obj_set_height(cui_PlayerKickButton, 25);
    lv_obj_set_align(cui_PlayerKickButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_PlayerKickButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_PlayerKickButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_PlayerKickButton, lv_color_hex(0xB53838), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_PlayerKickButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PLAYERKICKPANEL_NUM);
    children[UI_COMP_PLAYERKICKPANEL_PLAYERKICKPANEL] = cui_PlayerKickPanel;
    children[UI_COMP_PLAYERKICKPANEL_PLAYERKICKLABEL] = cui_PlayerKickLabel;
    children[UI_COMP_PLAYERKICKPANEL_PLAYERKICKBUTTON] = cui_PlayerKickButton;
    lv_obj_add_event_cb(cui_PlayerKickPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_PlayerKickPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_PlayerKickButton, ui_event_comp_PlayerKickPanel_PlayerKickButton, LV_EVENT_ALL, children);
    ui_comp_PlayerKickPanel_create_hook(cui_PlayerKickPanel);
    return cui_PlayerKickPanel;
}

