// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#include "../ui.h"

void ui_comp_OptionButton_create_hook(lv_obj_t * comp)
{
}

void ui_comp_PlayerKickPanel_create_hook(lv_obj_t * comp)
{
}
