// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#ifndef _UI_COMP_PLAYERKICKPANEL_H
#define _UI_COMP_PLAYERKICKPANEL_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT PlayerKickPanel
#define UI_COMP_PLAYERKICKPANEL_PLAYERKICKPANEL 0
#define UI_COMP_PLAYERKICKPANEL_PLAYERKICKLABEL 1
#define UI_COMP_PLAYERKICKPANEL_PLAYERKICKBUTTON 2
#define _UI_COMP_PLAYERKICKPANEL_NUM 3
lv_obj_t * ui_PlayerKickPanel_create(lv_obj_t * comp_parent);
void ui_event_comp_PlayerKickPanel_PlayerKickButton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
