// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#ifndef _UI_COMP_OPTIONBUTTON_H
#define _UI_COMP_OPTIONBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT OptionButton
#define UI_COMP_OPTIONBUTTON_OPTIONBUTTON 0
#define UI_COMP_OPTIONBUTTON_OPTIONLABEL 1
#define _UI_COMP_OPTIONBUTTON_NUM 2
lv_obj_t * ui_OptionButton_create(lv_obj_t * comp_parent);
void ui_event_comp_OptionButton_OptionButton(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
