// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: dndv_select

#include "ui_pc_sync/ui.h"
#include "ui/ui_helpers.h"

#include "dndv_sync.h"

///////////////////// VARIABLES ////////////////////


//lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////


///////////////////// SCREENS ////////////////////

void ui_pc_sync_init(void)
{
    //lv_disp_t * dispp = lv_disp_get_default();
    //lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               //true, LV_FONT_DEFAULT);
   // lv_disp_set_theme(dispp, theme);

    //ui____initial_actions0 = lv_obj_create(NULL);
    //ALSO Comment out ui____initial_actions0 in ui.h
    //lv_disp_load_scr(ui_Select_GM_Screen);
}
