// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: dndv_select

#ifndef _DNDV_PC_SYNC_UI_H
#define _DNDV_PC_SYNC_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui/ui_helpers.h"
#include "ui_events.h"
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
