// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: dndv_select

#ifndef _DNDV_PC_SYNC_UI_H
#define _DNDV_PC_SYNC_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui/ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Select_GM_Screen
void ui_Select_GM_Screen_screen_init(void);
extern lv_obj_t * ui_Select_GM_Screen;
void ui_event_Select_GM_Button(lv_event_t * e);
extern lv_obj_t * ui_Select_GM_Button;
// SCREEN: ui_Input_Key_Screen
void ui_Input_Key_Screen_screen_init(void);
extern lv_obj_t * ui_Input_Key_Screen;
void ui_event_Input_Key_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Input_Key_Keyboard;
extern lv_obj_t * ui_Input_Key_Text_Area;
// SCREEN: ui_Choose_PC_Screen
void ui_Choose_PC_Screen_screen_init(void);
extern lv_obj_t * ui_Choose_PC_Screen;
void ui_event_Choose_PC_Button(lv_event_t * e);
extern lv_obj_t * ui_Choose_PC_Button;
// SCREEN: ui_Ready_To_Start_Screen
void ui_Ready_To_Start_Screen_screen_init(void);
extern lv_obj_t * ui_Ready_To_Start_Screen;
extern lv_obj_t * ui_Name_Label;
extern lv_obj_t * ui_PC_Label;
void ui_event_Begin_Game_Button(lv_event_t * e);
extern lv_obj_t * ui_Begin_Game_Button;
//extern lv_obj_t * ui____initial_actions0;

void ui_pc_sync_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
