// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: dndv_select

#include "ui.h"
#include <stdio.h>

void ReadyToPlay(lv_event_t * e)
{
	printf("LET'S DO THIS!");
}
