// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Stage1_IS_HP_PP_PPP

#include "../ui.h"

void ui_HealthProfile_screen_init(void)
{
    ui_HealthProfile = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HealthProfile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_Bck = lv_obj_create(ui_HealthProfile);
    lv_obj_set_width(ui_HP_Bck, 318);
    lv_obj_set_height(ui_HP_Bck, 238);
    lv_obj_set_align(ui_HP_Bck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_Bck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HP_Bck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_Bck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpBck = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_hpBck, 110);
    lv_obj_set_height(ui_HP_hpBck, 110);
    lv_obj_set_x(ui_HP_hpBck, 70);
    lv_obj_set_y(ui_HP_hpBck, -18);
    lv_obj_set_align(ui_HP_hpBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_hpBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HP_hpBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HP_hpBck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMaxFill = lv_bar_create(ui_HP_hpBck);
    lv_bar_set_value(ui_HP_hpMaxFill, 90, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HP_hpMaxFill, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HP_hpMaxFill, 98);
    lv_obj_set_height(ui_HP_hpMaxFill, 99);
    lv_obj_set_align(ui_HP_hpMaxFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_HP_hpMaxFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpMaxFill, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpMaxFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HP_hpMaxFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpMaxFill, lv_color_hex(0x393939), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpMaxFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HP_hpFill = lv_bar_create(ui_HP_hpMaxFill);
    lv_bar_set_value(ui_HP_hpFill, 75, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HP_hpFill, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HP_hpFill, 98);
    lv_obj_set_height(ui_HP_hpFill, 99);
    lv_obj_set_align(ui_HP_hpFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_HP_hpFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpFill, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HP_hpFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpFill, lv_color_hex(0xFF0009), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HP_hpFill, lv_color_hex(0xBE0006), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_HP_hpFill, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_HP_hpFill, 180, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HP_hpFill, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HP_hpTempFill = lv_bar_create(ui_HP_hpFill);
    lv_bar_set_value(ui_HP_hpTempFill, 30, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HP_hpTempFill, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HP_hpTempFill, 98);
    lv_obj_set_height(ui_HP_hpTempFill, 99);
    lv_obj_set_align(ui_HP_hpTempFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_HP_hpTempFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpTempFill, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpTempFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_HP_hpTempFill, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HP_hpTempFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpTempFill, lv_color_hex(0xE6FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpTempFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HP_hpTempFill, lv_color_hex(0xFF7A00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_HP_hpTempFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_HP_hpTempFill, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HP_hpTempFill, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_HP_hpTempFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HP_hpHeart = lv_img_create(ui_HP_hpBck);
    lv_img_set_src(ui_HP_hpHeart, &ui_img_final_heart_png);
    lv_obj_set_width(ui_HP_hpHeart, LV_SIZE_CONTENT);   /// 169
    lv_obj_set_height(ui_HP_hpHeart, LV_SIZE_CONTENT);    /// 169
    lv_obj_set_align(ui_HP_hpHeart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HP_hpHeart, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HP_hpHeart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HP_hpHeart, 150);

    ui_HP_hpTotal = lv_label_create(ui_HP_hpHeart);
    lv_obj_set_width(ui_HP_hpTotal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpTotal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_hpTotal, 0);
    lv_obj_set_y(ui_HP_hpTotal, -8);
    lv_obj_set_align(ui_HP_hpTotal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_hpTotal, "42");
    lv_obj_set_style_text_font(ui_HP_hpTotal, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpHeartBorder = lv_img_create(ui_HP_hpHeart);
    lv_img_set_src(ui_HP_hpHeartBorder, &ui_img_final_heart_border_png);
    lv_obj_set_width(ui_HP_hpHeartBorder, LV_SIZE_CONTENT);   /// 169
    lv_obj_set_height(ui_HP_hpHeartBorder, LV_SIZE_CONTENT);    /// 169
    lv_obj_set_align(ui_HP_hpHeartBorder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HP_hpHeartBorder, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HP_hpHeartBorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HP_hpHeartBorder, 149);
    lv_obj_set_style_img_recolor(ui_HP_hpHeartBorder, lv_color_hex(0x393839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_HP_hpHeartBorder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_restLongBtn = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_restLongBtn, 73);
    lv_obj_set_height(ui_HP_restLongBtn, 60);
    lv_obj_set_x(ui_HP_restLongBtn, 30);
    lv_obj_set_y(ui_HP_restLongBtn, 73);
    lv_obj_set_align(ui_HP_restLongBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_restLongBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_restLongTxt = lv_label_create(ui_HP_restLongBtn);
    lv_obj_set_width(ui_HP_restLongTxt, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_HP_restLongTxt, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_align(ui_HP_restLongTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_restLongTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_restLongTxt, "Long\nRest");
    lv_obj_set_style_text_align(ui_HP_restLongTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_restLongTxt, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_restShortBtn = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_restShortBtn, 73);
    lv_obj_set_height(ui_HP_restShortBtn, 60);
    lv_obj_set_x(ui_HP_restShortBtn, 112);
    lv_obj_set_y(ui_HP_restShortBtn, 73);
    lv_obj_set_align(ui_HP_restShortBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_restShortBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_restShortTxt = lv_label_create(ui_HP_restShortBtn);
    lv_obj_set_width(ui_HP_restShortTxt, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_HP_restShortTxt, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_align(ui_HP_restShortTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_restShortTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_restShortTxt, "Short\nRest");
    lv_obj_set_style_text_align(ui_HP_restShortTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_restShortTxt, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_title = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_title, 181);
    lv_obj_set_height(ui_HP_title, 30);
    lv_obj_set_x(ui_HP_title, -8);
    lv_obj_set_y(ui_HP_title, -97);
    lv_obj_set_align(ui_HP_title, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_titleTxt = lv_label_create(ui_HP_title);
    lv_obj_set_width(ui_HP_titleTxt, LV_SIZE_CONTENT);   /// 136
    lv_obj_set_height(ui_HP_titleTxt, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_HP_titleTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_titleTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_titleTxt, "Health Screen");
    lv_obj_set_style_text_align(ui_HP_titleTxt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_titleTxt, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_toScreen_PP = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_toScreen_PP, 45);
    lv_obj_set_height(ui_HP_toScreen_PP, 30);
    lv_obj_set_x(ui_HP_toScreen_PP, -129);
    lv_obj_set_y(ui_HP_toScreen_PP, -96);
    lv_obj_set_align(ui_HP_toScreen_PP, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_toScreen_PP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_profPic = lv_img_create(ui_HP_toScreen_PP);
    lv_img_set_src(ui_HP_profPic, &ui_img_playericons_icon_warlock_png);
    lv_obj_set_width(ui_HP_profPic, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_HP_profPic, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_HP_profPic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HP_profPic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HP_profPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HP_profPic, 70);

    ui_HP_toScreen_XX = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_toScreen_XX, 60);
    lv_obj_set_height(ui_HP_toScreen_XX, 30);
    lv_obj_set_x(ui_HP_toScreen_XX, 121);
    lv_obj_set_y(ui_HP_toScreen_XX, -97);
    lv_obj_set_align(ui_HP_toScreen_XX, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_toScreen_XX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_hpMoreBck = lv_obj_create(ui_HealthProfile);
    lv_obj_set_width(ui_HP_hpMoreBck, 133);
    lv_obj_set_height(ui_HP_hpMoreBck, 174);
    lv_obj_set_x(ui_HP_hpMoreBck, -82);
    lv_obj_set_y(ui_HP_hpMoreBck, 16);
    lv_obj_set_align(ui_HP_hpMoreBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_hpMoreBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_hpMoreTemp = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreTemp, 50);
    lv_obj_set_height(ui_HP_hpMoreTemp, 50);
    lv_obj_set_x(ui_HP_hpMoreTemp, 59);
    lv_obj_set_y(ui_HP_hpMoreTemp, -55);
    lv_obj_set_align(ui_HP_hpMoreTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_HP_hpMoreTemp, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreTemp, "10");
    lv_obj_add_flag(ui_HP_hpMoreTemp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_HP_hpMoreTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreTemp, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreTempTxt = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreTempTxt, 60);
    lv_obj_set_height(ui_HP_hpMoreTempTxt, 40);
    lv_obj_set_x(ui_HP_hpMoreTempTxt, -25);
    lv_obj_set_y(ui_HP_hpMoreTempTxt, -51);
    lv_obj_set_align(ui_HP_hpMoreTempTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_hpMoreTempTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreTempTxt, "Temp\nHP");
    lv_obj_add_flag(ui_HP_hpMoreTempTxt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_HP_hpMoreTempTxt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreTempTxt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreCurrent = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreCurrent, 50);
    lv_obj_set_height(ui_HP_hpMoreCurrent, 50);
    lv_obj_set_x(ui_HP_hpMoreCurrent, 59);
    lv_obj_set_y(ui_HP_hpMoreCurrent, 0);
    lv_obj_set_align(ui_HP_hpMoreCurrent, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_HP_hpMoreCurrent, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreCurrent, "32");
    lv_obj_add_flag(ui_HP_hpMoreCurrent, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_HP_hpMoreCurrent, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreCurrent, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreCurrentTxt = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreCurrentTxt, 60);
    lv_obj_set_height(ui_HP_hpMoreCurrentTxt, 40);
    lv_obj_set_x(ui_HP_hpMoreCurrentTxt, -25);
    lv_obj_set_y(ui_HP_hpMoreCurrentTxt, 4);
    lv_obj_set_align(ui_HP_hpMoreCurrentTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_hpMoreCurrentTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreCurrentTxt, "Current\nHP");
    lv_obj_add_flag(ui_HP_hpMoreCurrentTxt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_HP_hpMoreCurrentTxt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreCurrentTxt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreMax = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreMax, 50);
    lv_obj_set_height(ui_HP_hpMoreMax, 50);
    lv_obj_set_x(ui_HP_hpMoreMax, 59);
    lv_obj_set_y(ui_HP_hpMoreMax, 55);
    lv_obj_set_align(ui_HP_hpMoreMax, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_HP_hpMoreMax, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreMax, "52");
    lv_obj_add_flag(ui_HP_hpMoreMax, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_HP_hpMoreMax, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreMax, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreMaxTxt = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreMaxTxt, 60);
    lv_obj_set_height(ui_HP_hpMoreMaxTxt, 40);
    lv_obj_set_x(ui_HP_hpMoreMaxTxt, -25);
    lv_obj_set_y(ui_HP_hpMoreMaxTxt, 59);
    lv_obj_set_align(ui_HP_hpMoreMaxTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_hpMoreMaxTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreMaxTxt, "Max\nHP");
    lv_obj_add_flag(ui_HP_hpMoreMaxTxt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_HP_hpMoreMaxTxt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreMaxTxt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_numInput = lv_obj_create(ui_HealthProfile);
    lv_obj_set_width(ui_HP_numInput, 296);
    lv_obj_set_height(ui_HP_numInput, 173);
    lv_obj_set_x(ui_HP_numInput, 0);
    lv_obj_set_y(ui_HP_numInput, -19);
    lv_obj_set_align(ui_HP_numInput, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_HP_numInput, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_HP_numInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_numKeyboard = lv_keyboard_create(ui_HP_numInput);
    lv_keyboard_set_mode(ui_HP_numKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_HP_numKeyboard, 292);
    lv_obj_set_height(ui_HP_numKeyboard, 120);
    lv_obj_set_x(ui_HP_numKeyboard, 0);
    lv_obj_set_y(ui_HP_numKeyboard, 13);
    lv_obj_set_align(ui_HP_numKeyboard, LV_ALIGN_BOTTOM_MID);

    ui_HP_numConfirmBtn = lv_obj_create(ui_HP_numKeyboard);
    lv_obj_set_width(ui_HP_numConfirmBtn, 113);
    lv_obj_set_height(ui_HP_numConfirmBtn, 57);
    lv_obj_set_x(ui_HP_numConfirmBtn, 87);
    lv_obj_set_y(ui_HP_numConfirmBtn, lv_pct(-26));
    lv_obj_set_align(ui_HP_numConfirmBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_numConfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_numConfirmTxt = lv_label_create(ui_HP_numConfirmBtn);
    lv_obj_set_width(ui_HP_numConfirmTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_numConfirmTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HP_numConfirmTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_numConfirmTxt, "Confirm");
    lv_obj_set_style_text_font(ui_HP_numConfirmTxt, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_numTextArea = lv_textarea_create(ui_HP_numInput);
    lv_obj_set_width(ui_HP_numTextArea, 285);
    lv_obj_set_height(ui_HP_numTextArea, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_HP_numTextArea, 0);
    lv_obj_set_y(ui_HP_numTextArea, -61);
    lv_obj_set_align(ui_HP_numTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_HP_numTextArea, "Insert HP Amount    ");
    lv_textarea_set_one_line(ui_HP_numTextArea, true);
    lv_obj_clear_flag(ui_HP_numTextArea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_HP_numTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_numTextArea, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_HP_hpTotal, ui_event_HP_hpTotal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_restLongBtn, ui_event_HP_restLongBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_restShortBtn, ui_event_HP_restShortBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_toScreen_PP, ui_event_HP_toScreen_PP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_hpMoreTemp, ui_event_HP_hpMoreTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_hpMoreTempTxt, ui_event_HP_hpMoreTempTxt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_hpMoreCurrent, ui_event_HP_hpMoreCurrent, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_hpMoreCurrentTxt, ui_event_HP_hpMoreCurrentTxt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_hpMoreMax, ui_event_HP_hpMoreMax, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_hpMoreMaxTxt, ui_event_HP_hpMoreMaxTxt, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_HP_numKeyboard, ui_HP_numTextArea);
    lv_obj_add_event_cb(ui_HP_numConfirmBtn, ui_event_HP_numConfirmBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HealthProfile, ui_event_HealthProfile, LV_EVENT_ALL, NULL);

}
