// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PlayerProfile_New

#include "../ui.h"

void ui_HealthProfile_screen_init(void)
{
    ui_HealthProfile = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HealthProfile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_Bck = lv_obj_create(ui_HealthProfile);
    lv_obj_set_width(ui_HP_Bck, 318);
    lv_obj_set_height(ui_HP_Bck, 238);
    lv_obj_set_align(ui_HP_Bck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_Bck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HP_Bck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_Bck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpBck = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_hpBck, 110);
    lv_obj_set_height(ui_HP_hpBck, 110);
    lv_obj_set_x(ui_HP_hpBck, 70);
    lv_obj_set_y(ui_HP_hpBck, -8);
    lv_obj_set_align(ui_HP_hpBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_hpBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HP_hpBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HP_hpBck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpFill = lv_bar_create(ui_HP_hpBck);
    lv_bar_set_value(ui_HP_hpFill, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HP_hpFill, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HP_hpFill, 98);
    lv_obj_set_height(ui_HP_hpFill, 99);
    lv_obj_set_align(ui_HP_hpFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_HP_hpFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpFill, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HP_hpFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpFill, lv_color_hex(0xFF0009), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HP_hpFill, lv_color_hex(0xBE0006), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_HP_hpFill, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_HP_hpFill, 180, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HP_hpFill, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HP_hpTempFill = lv_bar_create(ui_HP_hpBck);
    lv_bar_set_value(ui_HP_hpTempFill, 20, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HP_hpTempFill, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HP_hpTempFill, 98);
    lv_obj_set_height(ui_HP_hpTempFill, 99);
    lv_obj_set_align(ui_HP_hpTempFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_HP_hpTempFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_HP_hpTempFill, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HP_hpTempFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpTempFill, lv_color_hex(0xF6FC78), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpTempFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HP_hpTempFill, lv_color_hex(0xF4F322), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_HP_hpTempFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_HP_hpTempFill, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HP_hpTempFill, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_HP_hpTempFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HP_hpReduceMax = lv_obj_create(ui_HP_hpBck);
    lv_obj_set_width(ui_HP_hpReduceMax, 99);
    lv_obj_set_height(ui_HP_hpReduceMax, 15);
    lv_obj_set_x(ui_HP_hpReduceMax, -1);
    lv_obj_set_y(ui_HP_hpReduceMax, -7);
    lv_obj_set_align(ui_HP_hpReduceMax, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_HP_hpReduceMax, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HP_hpReduceMax, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpReduceMax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpReduceMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HP_hpReduceMax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HP_hpReduceMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpHeart = lv_img_create(ui_HP_hpBck);
    lv_img_set_src(ui_HP_hpHeart, &ui_img_552092932);
    lv_obj_set_width(ui_HP_hpHeart, LV_SIZE_CONTENT);   /// 169
    lv_obj_set_height(ui_HP_hpHeart, LV_SIZE_CONTENT);    /// 169
    lv_obj_set_x(ui_HP_hpHeart, -1);
    lv_obj_set_y(ui_HP_hpHeart, 0);
    lv_obj_set_align(ui_HP_hpHeart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HP_hpHeart, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HP_hpHeart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HP_hpHeart, 150);

    ui_HP_hpTotal = lv_label_create(ui_HP_hpHeart);
    lv_obj_set_width(ui_HP_hpTotal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpTotal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_hpTotal, 0);
    lv_obj_set_y(ui_HP_hpTotal, -8);
    lv_obj_set_align(ui_HP_hpTotal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_hpTotal, "42");
    lv_obj_set_style_text_font(ui_HP_hpTotal, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_healBtn = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_healBtn, 147);
    lv_obj_set_height(ui_HP_healBtn, 44);
    lv_obj_set_x(ui_HP_healBtn, 70);
    lv_obj_set_y(ui_HP_healBtn, 80);
    lv_obj_set_align(ui_HP_healBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_healBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_healTxt = lv_label_create(ui_HP_healBtn);
    lv_obj_set_width(ui_HP_healTxt, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_HP_healTxt, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_align(ui_HP_healTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_healTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_healTxt, "Heal Self");
    lv_obj_set_style_text_align(ui_HP_healTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_healTxt, &ui_font_Black_Chancery_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_title = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_title, 181);
    lv_obj_set_height(ui_HP_title, 30);
    lv_obj_set_x(ui_HP_title, -8);
    lv_obj_set_y(ui_HP_title, -97);
    lv_obj_set_align(ui_HP_title, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_title, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_titleTxt = lv_label_create(ui_HP_title);
    lv_obj_set_width(ui_HP_titleTxt, LV_SIZE_CONTENT);   /// 136
    lv_obj_set_height(ui_HP_titleTxt, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_HP_titleTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_titleTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_titleTxt, "Health Screen");
    lv_obj_set_style_text_align(ui_HP_titleTxt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_titleTxt, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_toScreen_PP = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_toScreen_PP, 45);
    lv_obj_set_height(ui_HP_toScreen_PP, 30);
    lv_obj_set_x(ui_HP_toScreen_PP, -129);
    lv_obj_set_y(ui_HP_toScreen_PP, -96);
    lv_obj_set_align(ui_HP_toScreen_PP, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_toScreen_PP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_profPic = lv_img_create(ui_HP_toScreen_PP);
    lv_img_set_src(ui_HP_profPic, &ui_img_playericons_icon_warlock_png);
    lv_obj_set_width(ui_HP_profPic, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_HP_profPic, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_align(ui_HP_profPic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HP_profPic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HP_profPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HP_profPic, 35);

    ui_HP_toScreen_XX = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_toScreen_XX, 60);
    lv_obj_set_height(ui_HP_toScreen_XX, 30);
    lv_obj_set_x(ui_HP_toScreen_XX, 121);
    lv_obj_set_y(ui_HP_toScreen_XX, -97);
    lv_obj_set_align(ui_HP_toScreen_XX, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_toScreen_XX, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_hpMoreBck = lv_obj_create(ui_HealthProfile);
    lv_obj_set_width(ui_HP_hpMoreBck, 133);
    lv_obj_set_height(ui_HP_hpMoreBck, 174);
    lv_obj_set_x(ui_HP_hpMoreBck, -82);
    lv_obj_set_y(ui_HP_hpMoreBck, 15);
    lv_obj_set_align(ui_HP_hpMoreBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_hpMoreBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_hpMoreTemp = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreTemp, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_HP_hpMoreTemp, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_HP_hpMoreTemp, 54);
    lv_obj_set_y(ui_HP_hpMoreTemp, -55);
    lv_obj_set_align(ui_HP_hpMoreTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_HP_hpMoreTemp, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreTemp, "10");
    lv_obj_add_flag(ui_HP_hpMoreTemp, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_HP_hpMoreTemp, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreTemp, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreTempTxt = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreTempTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpMoreTempTxt, LV_SIZE_CONTENT);    /// -1
    lv_obj_set_x(ui_HP_hpMoreTempTxt, -25);
    lv_obj_set_y(ui_HP_hpMoreTempTxt, -55);
    lv_obj_set_align(ui_HP_hpMoreTempTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_hpMoreTempTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreTempTxt, "Temp\nHP");
    lv_obj_set_style_text_align(ui_HP_hpMoreTempTxt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreTempTxt, &ui_font_Black_Chancery_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreCurrent = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreCurrent, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_HP_hpMoreCurrent, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_HP_hpMoreCurrent, 53);
    lv_obj_set_y(ui_HP_hpMoreCurrent, 0);
    lv_obj_set_align(ui_HP_hpMoreCurrent, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_HP_hpMoreCurrent, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreCurrent, "32");
    lv_obj_add_flag(ui_HP_hpMoreCurrent, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_HP_hpMoreCurrent, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreCurrent, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreCurrentTxt = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreCurrentTxt, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_HP_hpMoreCurrentTxt, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_HP_hpMoreCurrentTxt, -25);
    lv_obj_set_y(ui_HP_hpMoreCurrentTxt, 0);
    lv_obj_set_align(ui_HP_hpMoreCurrentTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_hpMoreCurrentTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreCurrentTxt, "Current\nHP");
    lv_obj_set_style_text_align(ui_HP_hpMoreCurrentTxt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreCurrentTxt, &ui_font_Black_Chancery_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreMax = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreMax, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_HP_hpMoreMax, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_HP_hpMoreMax, 49);
    lv_obj_set_y(ui_HP_hpMoreMax, 55);
    lv_obj_set_align(ui_HP_hpMoreMax, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_HP_hpMoreMax, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreMax, "52");
    lv_obj_add_flag(ui_HP_hpMoreMax, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_HP_hpMoreMax, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreMax, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMoreMaxTxt = lv_label_create(ui_HP_hpMoreBck);
    lv_obj_set_width(ui_HP_hpMoreMaxTxt, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_HP_hpMoreMaxTxt, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_HP_hpMoreMaxTxt, -25);
    lv_obj_set_y(ui_HP_hpMoreMaxTxt, 55);
    lv_obj_set_align(ui_HP_hpMoreMaxTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_HP_hpMoreMaxTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_HP_hpMoreMaxTxt, "Max\nHP");
    lv_obj_set_style_text_align(ui_HP_hpMoreMaxTxt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpMoreMaxTxt, &ui_font_Black_Chancery_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_healInput = lv_obj_create(ui_HealthProfile);
    lv_obj_set_width(ui_HP_healInput, 296);
    lv_obj_set_height(ui_HP_healInput, 173);
    lv_obj_set_x(ui_HP_healInput, 0);
    lv_obj_set_y(ui_HP_healInput, -19);
    lv_obj_set_align(ui_HP_healInput, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_HP_healInput, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_HP_healInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_healKeyboard = lv_keyboard_create(ui_HP_healInput);
    lv_keyboard_set_mode(ui_HP_healKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_HP_healKeyboard, 292);
    lv_obj_set_height(ui_HP_healKeyboard, 120);
    lv_obj_set_x(ui_HP_healKeyboard, 0);
    lv_obj_set_y(ui_HP_healKeyboard, 13);
    lv_obj_set_align(ui_HP_healKeyboard, LV_ALIGN_BOTTOM_MID);

    ui_HP_healConfirmBtn = lv_obj_create(ui_HP_healKeyboard);
    lv_obj_set_width(ui_HP_healConfirmBtn, 113);
    lv_obj_set_height(ui_HP_healConfirmBtn, 57);
    lv_obj_set_x(ui_HP_healConfirmBtn, 87);
    lv_obj_set_y(ui_HP_healConfirmBtn, lv_pct(-26));
    lv_obj_set_align(ui_HP_healConfirmBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_healConfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_healConfirmTxt = lv_label_create(ui_HP_healConfirmBtn);
    lv_obj_set_width(ui_HP_healConfirmTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_healConfirmTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HP_healConfirmTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_healConfirmTxt, "Confirm");
    lv_obj_set_style_text_font(ui_HP_healConfirmTxt, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_healTextArea = lv_textarea_create(ui_HP_healInput);
    lv_obj_set_width(ui_HP_healTextArea, 285);
    lv_obj_set_height(ui_HP_healTextArea, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_HP_healTextArea, 0);
    lv_obj_set_y(ui_HP_healTextArea, -61);
    lv_obj_set_align(ui_HP_healTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_HP_healTextArea, "Insert Damage Amount    ");
    lv_textarea_set_one_line(ui_HP_healTextArea, true);
    lv_obj_clear_flag(ui_HP_healTextArea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_HP_healTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_healTextArea, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);



    lv_obj_add_event_cb(ui_HP_hpTotal, ui_event_HP_hpTotal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_healBtn, ui_event_HP_healBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_toScreen_PP, ui_event_HP_toScreen_PP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_hpMoreTemp, ui_event_HP_hpMoreTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_hpMoreCurrent, ui_event_HP_hpMoreCurrent, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HP_hpMoreMax, ui_event_HP_hpMoreMax, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_HP_healKeyboard, ui_HP_healTextArea);
    lv_obj_add_event_cb(ui_HP_healConfirmBtn, ui_event_HP_healConfirmBtn, LV_EVENT_ALL, NULL);

}
