// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: DnDevice_HpSide_New

#include "../ui.h"

void ui_hpInfoScrn_screen_init(){
    ui_hpInfoScrn = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_hpInfoScrn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_Bck = lv_obj_create(ui_hpInfoScrn);
    lv_obj_set_width(ui_HP_Bck, 300);
    lv_obj_set_height(ui_HP_Bck, 220);
    lv_obj_set_align(ui_HP_Bck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_Bck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HP_Bck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_Bck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpFill = lv_bar_create(ui_HP_Bck);
    lv_bar_set_range(ui_HP_hpFill, 0, 52);
    lv_bar_set_value(ui_HP_hpFill, 32, LV_ANIM_OFF);
    lv_obj_set_width(ui_HP_hpFill, 98);
    lv_obj_set_height(ui_HP_hpFill, 99);
    lv_obj_set_x(ui_HP_hpFill, 60);
    lv_obj_set_y(ui_HP_hpFill, -14);
    lv_obj_set_align(ui_HP_hpFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_HP_hpFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpFill, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_HP_hpFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpFill, lv_color_hex(0xFF0009), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HP_hpFill, lv_color_hex(0xBE0006), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_HP_hpFill, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_HP_hpFill, 180, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HP_hpFill, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HP_hpTempFill = lv_bar_create(ui_HP_hpFill);
    lv_bar_set_range(ui_HP_hpTempFill, 0, 52);
    lv_bar_set_value(ui_HP_hpTempFill, 10, LV_ANIM_OFF);
    lv_obj_set_width(ui_HP_hpTempFill, 99);
    lv_obj_set_height(ui_HP_hpTempFill, 100);
    lv_obj_set_align(ui_HP_hpTempFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_HP_hpTempFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_HP_hpTempFill, &ui_img_851249624, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_HP_hpTempFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_HP_hpTempFill, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpTempFill, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_HP_hpTempFill, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_radius(ui_HP_hpTempFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HP_hpTempFill, lv_color_hex(0xF6FC78), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpTempFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HP_hpTempFill, lv_color_hex(0xF4FE22), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_HP_hpTempFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_HP_hpTempFill, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HP_hpTempFill, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_HP_hpReduceMax = lv_obj_create(ui_HP_hpTempFill);
    lv_obj_set_width(ui_HP_hpReduceMax, 100);
    lv_obj_set_height(ui_HP_hpReduceMax, 13);
    lv_obj_set_x(ui_HP_hpReduceMax, 2);
    lv_obj_set_y(ui_HP_hpReduceMax, 5);
    lv_obj_set_align(ui_HP_hpReduceMax, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_HP_hpReduceMax, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HP_hpReduceMax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HP_hpReduceMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HP_hpReduceMax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HP_hpReduceMax, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpHeart = lv_img_create(ui_HP_hpTempFill);
    lv_img_set_src(ui_HP_hpHeart, &ui_img_552092932);
    lv_obj_set_width(ui_HP_hpHeart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpHeart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HP_hpHeart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HP_hpHeart, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HP_hpHeart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HP_hpHeart, 150);

    ui_HP_hpTotal = lv_label_create(ui_HP_hpHeart);
    lv_obj_set_width(ui_HP_hpTotal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpTotal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_hpTotal, lv_pct(0));
    lv_obj_set_y(ui_HP_hpTotal, lv_pct(-6));
    lv_obj_set_align(ui_HP_hpTotal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_hpTotal, "42");
    lv_obj_set_style_text_color(ui_HP_hpTotal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HP_hpTotal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_hpTotal, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_HeartPic = lv_img_create(ui_HP_hpFill);
    lv_img_set_src(ui_HP_HeartPic, &ui_img_552092932);
    lv_obj_set_width(ui_HP_HeartPic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_HeartPic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_HeartPic, -1);
    lv_obj_set_y(ui_HP_HeartPic, 0);
    lv_obj_set_align(ui_HP_HeartPic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HP_HeartPic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HP_HeartPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HP_HeartPic, 149);

    ui_HP_hpMax = lv_label_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_hpMax, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpMax, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_hpMax, lv_pct(20));
    lv_obj_set_y(ui_HP_hpMax, lv_pct(35));
    lv_obj_set_align(ui_HP_hpMax, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HP_hpMax, "52");
    lv_obj_set_style_text_font(ui_HP_hpMax, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpMaxTxt = lv_label_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_hpMaxTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpMaxTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_hpMaxTxt, lv_pct(-82));
    lv_obj_set_y(ui_HP_hpMaxTxt, lv_pct(35));
    lv_obj_set_align(ui_HP_hpMaxTxt, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HP_hpMaxTxt, "Max \nHP");
    lv_obj_set_style_text_font(ui_HP_hpMaxTxt, &ui_font_Black_Chancery_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpCurrent = lv_label_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_hpCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_hpCurrent, lv_pct(20));
    lv_obj_set_y(ui_HP_hpCurrent, lv_pct(4));
    lv_obj_set_align(ui_HP_hpCurrent, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HP_hpCurrent, "32");
    lv_obj_set_style_text_font(ui_HP_hpCurrent, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpCurrentTxt = lv_label_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_hpCurrentTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpCurrentTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_hpCurrentTxt, lv_pct(-82));
    lv_obj_set_y(ui_HP_hpCurrentTxt, lv_pct(4));
    lv_obj_set_align(ui_HP_hpCurrentTxt, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HP_hpCurrentTxt, "Current \n     HP");
    lv_obj_set_style_text_font(ui_HP_hpCurrentTxt, &ui_font_Black_Chancery_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpTemp = lv_label_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_hpTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_hpTemp, lv_pct(20));
    lv_obj_set_y(ui_HP_hpTemp, lv_pct(-27));
    lv_obj_set_align(ui_HP_hpTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HP_hpTemp, "10");
    lv_obj_set_style_text_font(ui_HP_hpTemp, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_hpTempTxt = lv_label_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_hpTempTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_hpTempTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HP_hpTempTxt, lv_pct(-82));
    lv_obj_set_y(ui_HP_hpTempTxt, lv_pct(-27));
    lv_obj_set_align(ui_HP_hpTempTxt, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_HP_hpTempTxt, "Temp\n  HP");
    lv_obj_set_style_text_font(ui_HP_hpTempTxt, &ui_font_Black_Chancery_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_healBtn = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_healBtn, 133);
    lv_obj_set_height(ui_HP_healBtn, 48);
    lv_obj_set_x(ui_HP_healBtn, 60);
    lv_obj_set_y(ui_HP_healBtn, lv_pct(37));
    lv_obj_set_align(ui_HP_healBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_healBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_healTxt = lv_label_create(ui_HP_healBtn);
    lv_obj_set_width(ui_HP_healTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_healTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HP_healTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_healTxt, "Heal Self");
    lv_obj_set_style_text_font(ui_HP_healTxt, &ui_font_Black_Chancery_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_titleBck = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_titleBck, 168);
    lv_obj_set_height(ui_HP_titleBck, 30);
    lv_obj_set_x(ui_HP_titleBck, -6);
    lv_obj_set_y(ui_HP_titleBck, -90);
    lv_obj_set_align(ui_HP_titleBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_titleBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_title = lv_label_create(ui_HP_titleBck);
    lv_obj_set_width(ui_HP_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HP_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_title, "Health Screen");
    lv_obj_set_style_text_font(ui_HP_title, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_toScreen_MS = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_toScreen_MS, 56);
    lv_obj_set_height(ui_HP_toScreen_MS, 30);
    lv_obj_set_x(ui_HP_toScreen_MS, 113);
    lv_obj_set_y(ui_HP_toScreen_MS, -90);
    lv_obj_set_align(ui_HP_toScreen_MS, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HP_toScreen_MS, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_HP_toScreen_MS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_toScreen_MS_pic = lv_img_create(ui_HP_toScreen_MS);
    lv_img_set_src(ui_HP_toScreen_MS_pic, &ui_img_smallhomebtn_png);
    lv_obj_set_width(ui_HP_toScreen_MS_pic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_toScreen_MS_pic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HP_toScreen_MS_pic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HP_toScreen_MS_pic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HP_toScreen_MS_pic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HP_toScreen_MS_pic, 210);

    ui_HP_toScreen_PP = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_toScreen_PP, 45);
    lv_obj_set_height(ui_HP_toScreen_PP, 30);
    lv_obj_set_x(ui_HP_toScreen_PP, -119);
    lv_obj_set_y(ui_HP_toScreen_PP, -90);
    lv_obj_set_align(ui_HP_toScreen_PP, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_toScreen_PP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_profPicArtificer = lv_img_create(ui_HP_toScreen_PP);
    lv_img_set_src(ui_profPicArtificer, &ui_img_playericons_icon_artificer_png);
    lv_obj_set_width(ui_profPicArtificer, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profPicArtificer, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_profPicArtificer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_profPicArtificer, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_profPicArtificer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_profPicArtificer, 35);

    ui_profPicWarlock = lv_img_create(ui_HP_toScreen_PP);
    lv_img_set_src(ui_profPicWarlock, &ui_img_playericons_icon_warlock_png);
    lv_obj_set_width(ui_profPicWarlock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_profPicWarlock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_profPicWarlock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_profPicWarlock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_profPicWarlock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_profPicWarlock, 35);

    ui_HP_healInput = lv_obj_create(ui_HP_Bck);
    lv_obj_set_width(ui_HP_healInput, 296);
    lv_obj_set_height(ui_HP_healInput, 175);
    lv_obj_set_x(ui_HP_healInput, 0);
    lv_obj_set_y(ui_HP_healInput, 12);
    lv_obj_set_align(ui_HP_healInput, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_HP_healInput, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_HP_healInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_healKeyboard = lv_keyboard_create(ui_HP_healInput);
    lv_keyboard_set_mode(ui_HP_healKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_HP_healKeyboard, 292);
    lv_obj_set_height(ui_HP_healKeyboard, 120);
    lv_obj_set_x(ui_HP_healKeyboard, 0);
    lv_obj_set_y(ui_HP_healKeyboard, 13);
    lv_obj_set_align(ui_HP_healKeyboard, LV_ALIGN_BOTTOM_MID);

    ui_HP_healTextArea = lv_textarea_create(ui_HP_healInput);
    lv_obj_set_width(ui_HP_healTextArea, 274);
    lv_obj_set_height(ui_HP_healTextArea, 35);
    lv_obj_set_x(ui_HP_healTextArea, 0);
    lv_obj_set_y(ui_HP_healTextArea, -58);
    lv_obj_set_align(ui_HP_healTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_HP_healTextArea, "Insert Amount To Heal    ");
    lv_obj_clear_flag(ui_HP_healTextArea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_HP_healTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HP_healTextArea, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HP_healConfirmBtn = lv_obj_create(ui_HP_healInput);
    lv_obj_set_width(ui_HP_healConfirmBtn, 114);
    lv_obj_set_height(ui_HP_healConfirmBtn, 58);
    lv_obj_set_x(ui_HP_healConfirmBtn, 87);
    lv_obj_set_y(ui_HP_healConfirmBtn, lv_pct(-3));
    lv_obj_set_align(ui_HP_healConfirmBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HP_healConfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_healConfirmTxt = lv_label_create(ui_HP_healConfirmBtn);
    lv_obj_set_width(ui_HP_healConfirmTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_healConfirmTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HP_healConfirmTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_healConfirmTxt, "Confirm");
    lv_obj_set_style_text_font(ui_HP_healConfirmTxt, &ui_font_Black_Chancery_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_HP_healBtn, ui_event_HP_healBtn, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_HP_healKeyboard, ui_HP_healTextArea);
    lv_obj_add_event_cb(ui_HP_healConfirmBtn, ui_event_HP_healConfirmBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_hpInfoScrn, ui_event_hpInfoScrn, LV_EVENT_ALL, NULL);

}
