// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#include "../ui.h"

void ui_InputGMDetailsDemoScreen_screen_init(void)
{
    ui_InputGMDetailsDemoScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_InputGMDetailsDemoScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InputGMDetailsAdventureName = lv_textarea_create(ui_InputGMDetailsDemoScreen);
    lv_obj_set_width(ui_InputGMDetailsAdventureName, lv_pct(92));
    lv_obj_set_height(ui_InputGMDetailsAdventureName, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_InputGMDetailsAdventureName, 0);
    lv_obj_set_y(ui_InputGMDetailsAdventureName, -45);
    lv_obj_set_align(ui_InputGMDetailsAdventureName, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_InputGMDetailsAdventureName, "Placeholder...");
    lv_textarea_set_one_line(ui_InputGMDetailsAdventureName, true);

    ui_InputGMDetailsTitleLabel = lv_label_create(ui_InputGMDetailsDemoScreen);
    lv_obj_set_width(ui_InputGMDetailsTitleLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InputGMDetailsTitleLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InputGMDetailsTitleLabel, 1);
    lv_obj_set_y(ui_InputGMDetailsTitleLabel, -99);
    lv_obj_set_align(ui_InputGMDetailsTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InputGMDetailsTitleLabel, "Default GM Loaded. Enter Information:");

    ui_InputGMDetailsAdventureLabel = lv_label_create(ui_InputGMDetailsDemoScreen);
    lv_obj_set_width(ui_InputGMDetailsAdventureLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_InputGMDetailsAdventureLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_InputGMDetailsAdventureLabel, -8);
    lv_obj_set_y(ui_InputGMDetailsAdventureLabel, -76);
    lv_obj_set_align(ui_InputGMDetailsAdventureLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_InputGMDetailsAdventureLabel, "Adventure Name:");

    ui_InputGMDetailsKeyboard = lv_keyboard_create(ui_InputGMDetailsDemoScreen);
    lv_obj_set_width(ui_InputGMDetailsKeyboard, lv_pct(100));
    lv_obj_set_height(ui_InputGMDetailsKeyboard, lv_pct(60));
    lv_obj_set_x(ui_InputGMDetailsKeyboard, 0);
    lv_obj_set_y(ui_InputGMDetailsKeyboard, lv_pct(20));
    lv_obj_set_align(ui_InputGMDetailsKeyboard, LV_ALIGN_CENTER);

    lv_keyboard_set_textarea(ui_InputGMDetailsKeyboard, ui_InputGMDetailsAdventureName);
    lv_obj_add_event_cb(ui_InputGMDetailsKeyboard, ui_event_InputGMDetailsKeyboard, LV_EVENT_ALL, NULL);

}
