// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Stage1_IS_HP_PP_PPP

#include "../ui.h"

void ui_IntroScreen_screen_init(void)
{
    ui_IntroScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IntroScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IS_Bck = lv_obj_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_Bck, 318);
    lv_obj_set_height(ui_IS_Bck, 238);
    lv_obj_set_align(ui_IS_Bck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_IS_Bck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IS_introText_D1 = lv_label_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_introText_D1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IS_introText_D1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IS_introText_D1, -86);
    lv_obj_set_y(ui_IS_introText_D1, 0);
    lv_obj_set_align(ui_IS_introText_D1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IS_introText_D1, "D");
    lv_obj_set_style_text_font(ui_IS_introText_D1, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IS_introText_N1 = lv_label_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_introText_N1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IS_introText_N1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IS_introText_N1, -48);
    lv_obj_set_y(ui_IS_introText_N1, 0);
    lv_obj_set_align(ui_IS_introText_N1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IS_introText_N1, "n");
    lv_obj_set_style_text_font(ui_IS_introText_N1, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IS_introText_D2 = lv_label_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_introText_D2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IS_introText_D2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IS_introText_D2, -12);
    lv_obj_set_y(ui_IS_introText_D2, 0);
    lv_obj_set_align(ui_IS_introText_D2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IS_introText_D2, "D");
    lv_obj_set_style_text_font(ui_IS_introText_D2, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IS_introText_E1 = lv_label_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_introText_E1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IS_introText_E1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IS_introText_E1, 23);
    lv_obj_set_y(ui_IS_introText_E1, 0);
    lv_obj_set_align(ui_IS_introText_E1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IS_introText_E1, "e");
    lv_obj_set_style_text_font(ui_IS_introText_E1, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IS_introText_V1 = lv_label_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_introText_V1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IS_introText_V1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IS_introText_V1, 46);
    lv_obj_set_y(ui_IS_introText_V1, 0);
    lv_obj_set_align(ui_IS_introText_V1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IS_introText_V1, "v");
    lv_obj_set_style_text_font(ui_IS_introText_V1, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IS_introText_I1 = lv_label_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_introText_I1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IS_introText_I1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IS_introText_I1, 64);
    lv_obj_set_y(ui_IS_introText_I1, 0);
    lv_obj_set_align(ui_IS_introText_I1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IS_introText_I1, "i");
    lv_obj_set_style_text_font(ui_IS_introText_I1, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IS_introText_C1 = lv_label_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_introText_C1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IS_introText_C1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IS_introText_C1, 80);
    lv_obj_set_y(ui_IS_introText_C1, 0);
    lv_obj_set_align(ui_IS_introText_C1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IS_introText_C1, "c");
    lv_obj_set_style_text_font(ui_IS_introText_C1, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IS_introText_E2 = lv_label_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_introText_E2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IS_introText_E2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IS_introText_E2, 101);
    lv_obj_set_y(ui_IS_introText_E2, 0);
    lv_obj_set_align(ui_IS_introText_E2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IS_introText_E2, "e");
    lv_obj_set_style_text_font(ui_IS_introText_E2, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IS_continueTxt = lv_label_create(ui_IntroScreen);
    lv_obj_set_width(ui_IS_continueTxt, 0);
    lv_obj_set_height(ui_IS_continueTxt, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_IS_continueTxt, 0);
    lv_obj_set_y(ui_IS_continueTxt, 80);
    lv_obj_set_align(ui_IS_continueTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_IS_continueTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_IS_continueTxt, "Touch Screen to Start");
    lv_obj_set_style_text_align(ui_IS_continueTxt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IS_continueTxt, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_IS_Bck, ui_event_IS_Bck, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_IntroScreen, ui_event_IntroScreen, LV_EVENT_ALL, NULL);

}
