// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Stage1_IS_HP_PP_PPP

#include "../ui.h"

void ui_PlayerCreation_screen_init(void)
{
    ui_PlayerCreation = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PlayerCreation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PC_Bck = lv_obj_create(ui_PlayerCreation);
    lv_obj_set_width(ui_PC_Bck, 318);
    lv_obj_set_height(ui_PC_Bck, 238);
    lv_obj_set_align(ui_PC_Bck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PC_Bck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PC_Bck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PC_Bck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_profPic = lv_img_create(ui_PC_Bck);
    lv_img_set_src(ui_PC_profPic, &ui_img_playericons_icon_warlock_png);
    lv_obj_set_width(ui_PC_profPic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PC_profPic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PC_profPic, 0);
    lv_obj_set_y(ui_PC_profPic, 6);
    lv_obj_set_align(ui_PC_profPic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PC_profPic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PC_profPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PC_profPic, 150);

    ui_PC_condNextBtn = lv_obj_create(ui_PC_Bck);
    lv_obj_set_width(ui_PC_condNextBtn, 30);
    lv_obj_set_height(ui_PC_condNextBtn, 110);
    lv_obj_set_x(ui_PC_condNextBtn, 89);
    lv_obj_set_y(ui_PC_condNextBtn, 3);
    lv_obj_set_align(ui_PC_condNextBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PC_condNextBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PC_condNextTxt = lv_label_create(ui_PC_condNextBtn);
    lv_obj_set_width(ui_PC_condNextTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PC_condNextTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PC_condNextTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PC_condNextTxt, ">");
    lv_obj_set_style_text_font(ui_PC_condNextTxt, &ui_font_Dungeon_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_condLastBtn = lv_obj_create(ui_PC_Bck);
    lv_obj_set_width(ui_PC_condLastBtn, 30);
    lv_obj_set_height(ui_PC_condLastBtn, 110);
    lv_obj_set_x(ui_PC_condLastBtn, -90);
    lv_obj_set_y(ui_PC_condLastBtn, 5);
    lv_obj_set_align(ui_PC_condLastBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PC_condLastBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PC_condLastTxt = lv_label_create(ui_PC_condLastBtn);
    lv_obj_set_width(ui_PC_condLastTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PC_condLastTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PC_condLastTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PC_condLastTxt, "<");
    lv_obj_set_style_text_font(ui_PC_condLastTxt, &ui_font_Dungeon_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_confirmBck = lv_obj_create(ui_PC_Bck);
    lv_obj_set_width(ui_PC_confirmBck, 279);
    lv_obj_set_height(ui_PC_confirmBck, 30);
    lv_obj_set_x(ui_PC_confirmBck, -1);
    lv_obj_set_y(ui_PC_confirmBck, 93);
    lv_obj_set_align(ui_PC_confirmBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PC_confirmBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PC_confirmTxt = lv_label_create(ui_PC_confirmBck);
    lv_obj_set_width(ui_PC_confirmTxt, LV_SIZE_CONTENT);   /// 136
    lv_obj_set_height(ui_PC_confirmTxt, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_PC_confirmTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PC_confirmTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_PC_confirmTxt, "Looks Good, Continue");
    lv_obj_set_style_text_align(ui_PC_confirmTxt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PC_confirmTxt, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_numInput = lv_obj_create(ui_PC_Bck);
    lv_obj_set_width(ui_PC_numInput, 296);
    lv_obj_set_height(ui_PC_numInput, 173);
    lv_obj_set_x(ui_PC_numInput, 0);
    lv_obj_set_y(ui_PC_numInput, 9);
    lv_obj_set_align(ui_PC_numInput, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_PC_numInput, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PC_numInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PC_numKeyboard = lv_keyboard_create(ui_PC_numInput);
    lv_keyboard_set_mode(ui_PC_numKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_PC_numKeyboard, 292);
    lv_obj_set_height(ui_PC_numKeyboard, 120);
    lv_obj_set_x(ui_PC_numKeyboard, 0);
    lv_obj_set_y(ui_PC_numKeyboard, 13);
    lv_obj_set_align(ui_PC_numKeyboard, LV_ALIGN_BOTTOM_MID);

    ui_PC_numConfirmBtn = lv_obj_create(ui_PC_numKeyboard);
    lv_obj_set_width(ui_PC_numConfirmBtn, 113);
    lv_obj_set_height(ui_PC_numConfirmBtn, 57);
    lv_obj_set_x(ui_PC_numConfirmBtn, 87);
    lv_obj_set_y(ui_PC_numConfirmBtn, lv_pct(-26));
    lv_obj_set_align(ui_PC_numConfirmBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PC_numConfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HP_numConfirmTxt2 = lv_label_create(ui_PC_numConfirmBtn);
    lv_obj_set_width(ui_HP_numConfirmTxt2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HP_numConfirmTxt2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HP_numConfirmTxt2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HP_numConfirmTxt2, "Confirm");
    lv_obj_set_style_text_font(ui_HP_numConfirmTxt2, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_numTextArea = lv_textarea_create(ui_PC_numInput);
    lv_obj_set_width(ui_PC_numTextArea, 285);
    lv_obj_set_height(ui_PC_numTextArea, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PC_numTextArea, 0);
    lv_obj_set_y(ui_PC_numTextArea, -61);
    lv_obj_set_align(ui_PC_numTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PC_numTextArea, "Insert HP Amount    ");
    lv_textarea_set_one_line(ui_PC_numTextArea, true);
    lv_obj_clear_flag(ui_PC_numTextArea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_PC_numTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PC_numTextArea, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_PC_wordInput = lv_obj_create(ui_PC_Bck);
    lv_obj_set_width(ui_PC_wordInput, 296);
    lv_obj_set_height(ui_PC_wordInput, 173);
    lv_obj_set_x(ui_PC_wordInput, 0);
    lv_obj_set_y(ui_PC_wordInput, 9);
    lv_obj_set_align(ui_PC_wordInput, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_PC_wordInput, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PC_wordInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PC_wordKeyboard = lv_keyboard_create(ui_PC_wordInput);
    lv_keyboard_set_mode(ui_PC_wordKeyboard, LV_KEYBOARD_MODE_TEXT_UPPER);
    lv_obj_set_width(ui_PC_wordKeyboard, 292);
    lv_obj_set_height(ui_PC_wordKeyboard, 120);
    lv_obj_set_x(ui_PC_wordKeyboard, 0);
    lv_obj_set_y(ui_PC_wordKeyboard, 13);
    lv_obj_set_align(ui_PC_wordKeyboard, LV_ALIGN_BOTTOM_MID);

    ui_PC_wordConfirmBtn = lv_obj_create(ui_PC_wordKeyboard);
    lv_obj_set_width(ui_PC_wordConfirmBtn, 37);
    lv_obj_set_height(ui_PC_wordConfirmBtn, 26);
    lv_obj_set_x(ui_PC_wordConfirmBtn, 124);
    lv_obj_set_y(ui_PC_wordConfirmBtn, lv_pct(38));
    lv_obj_set_align(ui_PC_wordConfirmBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PC_wordConfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_PC_wordConfirmBtn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_wordTextArea = lv_textarea_create(ui_PC_wordInput);
    lv_obj_set_width(ui_PC_wordTextArea, 285);
    lv_obj_set_height(ui_PC_wordTextArea, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PC_wordTextArea, 0);
    lv_obj_set_y(ui_PC_wordTextArea, -61);
    lv_obj_set_align(ui_PC_wordTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PC_wordTextArea, "Insert Player Name   ");
    lv_textarea_set_one_line(ui_PC_wordTextArea, true);
    lv_obj_clear_flag(ui_PC_wordTextArea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_PC_wordTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PC_wordTextArea, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_PC_nameTxt = lv_label_create(ui_PlayerCreation);
    lv_obj_set_width(ui_PC_nameTxt, 216);
    lv_obj_set_height(ui_PC_nameTxt, 18);
    lv_obj_set_x(ui_PC_nameTxt, -36);
    lv_obj_set_y(ui_PC_nameTxt, -100);
    lv_obj_set_align(ui_PC_nameTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PC_nameTxt, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_PC_nameTxt, "Bharstynox Ironfist");
    lv_obj_add_flag(ui_PC_nameTxt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_PC_nameTxt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PC_nameTxt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_hpTxt = lv_label_create(ui_PlayerCreation);
    lv_obj_set_width(ui_PC_hpTxt, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_PC_hpTxt, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_PC_hpTxt, 284);
    lv_obj_set_y(ui_PC_hpTxt, -100);
    lv_obj_set_align(ui_PC_hpTxt, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_PC_hpTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_PC_hpTxt, "158");
    lv_obj_add_flag(ui_PC_hpTxt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_PC_hpTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PC_hpTxt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_hpLabel = lv_label_create(ui_PlayerCreation);
    lv_obj_set_width(ui_PC_hpLabel, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_PC_hpLabel, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_PC_hpLabel, -40);
    lv_obj_set_y(ui_PC_hpLabel, -100);
    lv_obj_set_align(ui_PC_hpLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_PC_hpLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_PC_hpLabel, "HP:");
    lv_obj_add_flag(ui_PC_hpLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_PC_hpLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PC_hpLabel, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_acTxt = lv_label_create(ui_PlayerCreation);
    lv_obj_set_width(ui_PC_acTxt, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_PC_acTxt, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_PC_acTxt, 284);
    lv_obj_set_y(ui_PC_acTxt, -76);
    lv_obj_set_align(ui_PC_acTxt, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_PC_acTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_PC_acTxt, "15");
    lv_obj_add_flag(ui_PC_acTxt, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_PC_acTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PC_acTxt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PC_acLabel = lv_label_create(ui_PlayerCreation);
    lv_obj_set_width(ui_PC_acLabel, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_PC_acLabel, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_x(ui_PC_acLabel, -40);
    lv_obj_set_y(ui_PC_acLabel, -76);
    lv_obj_set_align(ui_PC_acLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_PC_acLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_PC_acLabel, "AC:");
    lv_obj_add_flag(ui_PC_acLabel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_PC_acLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PC_acLabel, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PC_condNextBtn, ui_event_PC_condNextBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PC_condLastBtn, ui_event_PC_condLastBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PC_confirmBck, ui_event_PC_confirmBck, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_PC_numKeyboard, ui_PC_numTextArea);
    lv_obj_add_event_cb(ui_PC_numConfirmBtn, ui_event_PC_numConfirmBtn, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_PC_wordKeyboard, ui_PC_wordTextArea);
    lv_obj_add_event_cb(ui_PC_wordConfirmBtn, ui_event_PC_wordConfirmBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PC_wordKeyboard, ui_event_PC_wordKeyboard, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PC_nameTxt, ui_event_PC_nameTxt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PC_hpTxt, ui_event_PC_hpTxt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PC_hpLabel, ui_event_PC_hpLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PC_acTxt, ui_event_PC_acTxt, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PC_acLabel, ui_event_PC_acLabel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayerCreation, ui_event_PlayerCreation, LV_EVENT_ALL, NULL);

}
