// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Stage1_IS_HP_PP_PPP

#include "../ui.h"

void ui_PlayerProfile_screen_init(void)
{
    ui_PlayerProfile = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PlayerProfile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PP_Bck = lv_obj_create(ui_PlayerProfile);
    lv_obj_set_width(ui_PP_Bck, 318);
    lv_obj_set_height(ui_PP_Bck, 238);
    lv_obj_set_align(ui_PP_Bck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_Bck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PP_condBck = lv_obj_create(ui_PP_Bck);
    lv_obj_set_width(ui_PP_condBck, 290);
    lv_obj_set_height(ui_PP_condBck, 38);
    lv_obj_set_x(ui_PP_condBck, 0);
    lv_obj_set_y(ui_PP_condBck, 84);
    lv_obj_set_align(ui_PP_condBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_condBck, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_condBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_condBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_cond0 = lv_img_create(ui_PP_condBck);
    lv_img_set_src(ui_PP_cond0, &ui_img_conditions_new_blinded_png);
    lv_obj_set_width(ui_PP_cond0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_cond0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PP_cond0, -90);
    lv_obj_set_y(ui_PP_cond0, 0);
    lv_obj_set_align(ui_PP_cond0, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PP_cond0, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PP_cond0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_cond0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_cond0, 200);
    lv_obj_set_style_blend_mode(ui_PP_cond0, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_user_data(ui_PP_cond0,0);

    ui_PP_cond1 = lv_img_create(ui_PP_condBck);
    lv_img_set_src(ui_PP_cond1, &ui_img_conditions_new_charmed_png);
    lv_obj_set_width(ui_PP_cond1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_cond1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PP_cond1, -55);
    lv_obj_set_y(ui_PP_cond1, 0);
    lv_obj_set_align(ui_PP_cond1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PP_cond1, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PP_cond1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_cond1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_cond1, 200);
    lv_obj_set_style_blend_mode(ui_PP_cond1, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_cond2 = lv_img_create(ui_PP_condBck);
    lv_img_set_src(ui_PP_cond2, &ui_img_conditions_new_deafened_png);
    lv_obj_set_width(ui_PP_cond2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_cond2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PP_cond2, -20);
    lv_obj_set_y(ui_PP_cond2, 0);
    lv_obj_set_align(ui_PP_cond2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PP_cond2, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PP_cond2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_cond2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_cond2, 200);
    lv_obj_set_style_blend_mode(ui_PP_cond2, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_cond3 = lv_img_create(ui_PP_condBck);
    lv_img_set_src(ui_PP_cond3, &ui_img_conditions_new_exhausion_png);
    lv_obj_set_width(ui_PP_cond3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_cond3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PP_cond3, 15);
    lv_obj_set_y(ui_PP_cond3, 0);
    lv_obj_set_align(ui_PP_cond3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PP_cond3, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PP_cond3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_cond3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_cond3, 200);
    lv_obj_set_style_blend_mode(ui_PP_cond3, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_condExhaustionNumBck = lv_obj_create(ui_PP_cond3);
    lv_obj_set_width(ui_PP_condExhaustionNumBck, 10);
    lv_obj_set_height(ui_PP_condExhaustionNumBck, 12);
    lv_obj_set_x(ui_PP_condExhaustionNumBck, -9);
    lv_obj_set_y(ui_PP_condExhaustionNumBck, -9);
    lv_obj_set_align(ui_PP_condExhaustionNumBck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_condExhaustionNumBck, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PP_condExhaustionNumBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PP_condExhaustionNumBck, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PP_condExhaustionNumBck, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_condExhaustionNumBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PP_condExhaustionNumBck, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PP_condExhaustionNumBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PP_condExhaustionNumBck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PP_condExhaustionNumBck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PP_condExhaustionNumBck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_condExhaustionNum = lv_label_create(ui_PP_condExhaustionNumBck);
    lv_obj_set_width(ui_PP_condExhaustionNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_condExhaustionNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_condExhaustionNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_condExhaustionNum, "2");
    lv_obj_set_style_text_color(ui_PP_condExhaustionNum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_condExhaustionNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_condExhaustionNum, &ui_font_Black_Chancery_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_cond4 = lv_img_create(ui_PP_condBck);
    lv_img_set_src(ui_PP_cond4, &ui_img_conditions_new_frightened_png);
    lv_obj_set_width(ui_PP_cond4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_cond4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PP_cond4, 50);
    lv_obj_set_y(ui_PP_cond4, 0);
    lv_obj_set_align(ui_PP_cond4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PP_cond4, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PP_cond4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_cond4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_cond4, 200);
    lv_obj_set_style_blend_mode(ui_PP_cond4, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_condNextBtn = lv_obj_create(ui_PP_condBck);
    lv_obj_set_width(ui_PP_condNextBtn, 30);
    lv_obj_set_height(ui_PP_condNextBtn, 30);
    lv_obj_set_x(ui_PP_condNextBtn, 85);
    lv_obj_set_y(ui_PP_condNextBtn, 0);
    lv_obj_set_align(ui_PP_condNextBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_condNextBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PP_condNextTxt = lv_label_create(ui_PP_condNextBtn);
    lv_obj_set_width(ui_PP_condNextTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_condNextTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_condNextTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_condNextTxt, ">");
    lv_obj_set_style_text_font(ui_PP_condNextTxt, &ui_font_Dungeon_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_condPrevBtn = lv_obj_create(ui_PP_condBck);
    lv_obj_set_width(ui_PP_condPrevBtn, 30);
    lv_obj_set_height(ui_PP_condPrevBtn, 30);
    lv_obj_set_x(ui_PP_condPrevBtn, -125);
    lv_obj_set_y(ui_PP_condPrevBtn, 0);
    lv_obj_set_align(ui_PP_condPrevBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_condPrevBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PP_condPrevTxt = lv_label_create(ui_PP_condPrevBtn);
    lv_obj_set_width(ui_PP_condPrevTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_condPrevTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_condPrevTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_condPrevTxt, "<");
    lv_obj_set_style_text_font(ui_PP_condPrevTxt, &ui_font_Dungeon_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_condMoreBtn = lv_obj_create(ui_PP_condBck);
    lv_obj_set_width(ui_PP_condMoreBtn, 30);
    lv_obj_set_height(ui_PP_condMoreBtn, 30);
    lv_obj_set_x(ui_PP_condMoreBtn, 123);
    lv_obj_set_y(ui_PP_condMoreBtn, 0);
    lv_obj_set_align(ui_PP_condMoreBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_condMoreBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PP_condMoreTxt = lv_label_create(ui_PP_condMoreBtn);
    lv_obj_set_width(ui_PP_condMoreTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_condMoreTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PP_condMoreTxt, 0);
    lv_obj_set_y(ui_PP_condMoreTxt, -5);
    lv_obj_set_align(ui_PP_condMoreTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_condMoreTxt, "...");
    lv_obj_set_style_text_letter_space(ui_PP_condMoreTxt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_PP_condMoreTxt, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_condMoreTxt, &ui_font_Black_Chancery_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_profPicBck = lv_obj_create(ui_PP_Bck);
    lv_obj_set_width(ui_PP_profPicBck, 80);
    lv_obj_set_height(ui_PP_profPicBck, 80);
    lv_obj_set_x(ui_PP_profPicBck, -103);
    lv_obj_set_y(ui_PP_profPicBck, 10);
    lv_obj_set_align(ui_PP_profPicBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_profPicBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_profPicBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_profPicBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_profPic = lv_img_create(ui_PP_profPicBck);
    lv_img_set_src(ui_PP_profPic, &ui_img_playericons_icon_warlock_png);
    lv_obj_set_width(ui_PP_profPic, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_profPic, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_profPic, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_profPic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_profPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_profPic, 100);

    ui_PP_hpBck = lv_obj_create(ui_PP_Bck);
    lv_obj_set_width(ui_PP_hpBck, 80);
    lv_obj_set_height(ui_PP_hpBck, 80);
    lv_obj_set_x(ui_PP_hpBck, 0);
    lv_obj_set_y(ui_PP_hpBck, 10);
    lv_obj_set_align(ui_PP_hpBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_hpBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_hpBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_hpBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_hpMaxFill = lv_bar_create(ui_PP_hpBck);
    lv_bar_set_value(ui_PP_hpMaxFill, 90, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_PP_hpMaxFill, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_PP_hpMaxFill, 70);
    lv_obj_set_height(ui_PP_hpMaxFill, 71);
    lv_obj_set_align(ui_PP_hpMaxFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_PP_hpMaxFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PP_hpMaxFill, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_hpMaxFill, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PP_hpMaxFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PP_hpMaxFill, lv_color_hex(0x393939), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_hpMaxFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PP_hpFill = lv_bar_create(ui_PP_hpMaxFill);
    lv_bar_set_value(ui_PP_hpFill, 75, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_PP_hpFill, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_PP_hpFill, 70);
    lv_obj_set_height(ui_PP_hpFill, 71);
    lv_obj_set_align(ui_PP_hpFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_PP_hpFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PP_hpFill, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_hpFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PP_hpFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PP_hpFill, lv_color_hex(0xFF0009), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_hpFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PP_hpFill, lv_color_hex(0xBE0006), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PP_hpFill, 50, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PP_hpFill, 180, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PP_hpFill, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PP_hpTempFill = lv_bar_create(ui_PP_hpFill);
    lv_bar_set_value(ui_PP_hpTempFill, 30, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_PP_hpTempFill, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_PP_hpTempFill, 70);
    lv_obj_set_height(ui_PP_hpTempFill, 71);
    lv_obj_set_align(ui_PP_hpTempFill, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_PP_hpTempFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PP_hpTempFill, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_hpTempFill, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_PP_hpTempFill, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_PP_hpTempFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PP_hpTempFill, lv_color_hex(0xE6FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_hpTempFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_PP_hpTempFill, lv_color_hex(0xFF7A00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PP_hpTempFill, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PP_hpTempFill, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_PP_hpTempFill, LV_GRAD_DIR_VER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_PP_hpTempFill, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_PP_hpHeart = lv_img_create(ui_PP_hpBck);
    lv_img_set_src(ui_PP_hpHeart, &ui_img_final_heart_png);
    lv_obj_set_width(ui_PP_hpHeart, LV_SIZE_CONTENT);   /// 169
    lv_obj_set_height(ui_PP_hpHeart, LV_SIZE_CONTENT);    /// 169
    lv_obj_set_x(ui_PP_hpHeart, -1);
    lv_obj_set_y(ui_PP_hpHeart, 0);
    lv_obj_set_align(ui_PP_hpHeart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_hpHeart, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_hpHeart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_hpHeart, 107);

    ui_PP_hpTotal = lv_label_create(ui_PP_hpHeart);
    lv_obj_set_width(ui_PP_hpTotal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_hpTotal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PP_hpTotal, 0);
    lv_obj_set_y(ui_PP_hpTotal, -8);
    lv_obj_set_align(ui_PP_hpTotal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_hpTotal, "42");
    lv_obj_set_style_text_font(ui_PP_hpTotal, &ui_font_Black_Chancery_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_hpHeartBorder = lv_img_create(ui_PP_hpBck);
    lv_img_set_src(ui_PP_hpHeartBorder, &ui_img_final_heart_border_png);
    lv_obj_set_width(ui_PP_hpHeartBorder, LV_SIZE_CONTENT);   /// 169
    lv_obj_set_height(ui_PP_hpHeartBorder, LV_SIZE_CONTENT);    /// 169
    lv_obj_set_x(ui_PP_hpHeartBorder, -1);
    lv_obj_set_y(ui_PP_hpHeartBorder, 0);
    lv_obj_set_align(ui_PP_hpHeartBorder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_hpHeartBorder, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_hpHeartBorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_hpHeartBorder, 106);

    ui_PP_acBck = lv_obj_create(ui_PP_Bck);
    lv_obj_set_width(ui_PP_acBck, 80);
    lv_obj_set_height(ui_PP_acBck, 80);
    lv_obj_set_x(ui_PP_acBck, 103);
    lv_obj_set_y(ui_PP_acBck, 10);
    lv_obj_set_align(ui_PP_acBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_acBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_acBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_acBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_acCover_half = lv_img_create(ui_PP_acBck);
    lv_img_set_src(ui_PP_acCover_half, &ui_img_conditionextra_cover_half_png);
    lv_obj_set_width(ui_PP_acCover_half, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_acCover_half, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_acCover_half, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_acCover_half, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_acCover_half, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_acCover_half, 350);
    lv_obj_set_style_blend_mode(ui_PP_acCover_half, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_acCover_threeQuarter = lv_img_create(ui_PP_acBck);
    lv_img_set_src(ui_PP_acCover_threeQuarter, &ui_img_conditionextra_cover_threequarter_png);
    lv_obj_set_width(ui_PP_acCover_threeQuarter, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_acCover_threeQuarter, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_acCover_threeQuarter, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_acCover_threeQuarter, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_acCover_threeQuarter, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_acCover_threeQuarter, 350);
    lv_obj_set_style_blend_mode(ui_PP_acCover_threeQuarter, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_acCover_total = lv_img_create(ui_PP_acBck);
    lv_img_set_src(ui_PP_acCover_total, &ui_img_conditionextra_cover_total_png);
    lv_obj_set_width(ui_PP_acCover_total, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_acCover_total, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_acCover_total, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_acCover_total, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_acCover_total, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_acCover_total, 350);
    lv_obj_set_style_blend_mode(ui_PP_acCover_total, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_acShield = lv_img_create(ui_PP_acBck);
    lv_img_set_src(ui_PP_acShield, &ui_img_final_shield_png);
    lv_obj_set_width(ui_PP_acShield, LV_SIZE_CONTENT);   /// 169
    lv_obj_set_height(ui_PP_acShield, LV_SIZE_CONTENT);    /// 169
    lv_obj_set_align(ui_PP_acShield, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_acShield, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_acShield, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_acShield, 220);

    ui_PP_acTotal = lv_label_create(ui_PP_acShield);
    lv_obj_set_width(ui_PP_acTotal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_acTotal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_acTotal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_acTotal, "21");
    lv_obj_set_style_text_font(ui_PP_acTotal, &ui_font_Black_Chancery_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_acMath = lv_label_create(ui_PP_acShield);
    lv_obj_set_width(ui_PP_acMath, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_acMath, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PP_acMath, 0);
    lv_obj_set_y(ui_PP_acMath, -20);
    lv_obj_set_align(ui_PP_acMath, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_acMath, "17+2");
    lv_obj_set_style_text_font(ui_PP_acMath, &ui_font_Black_Chancery_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_acShieldBorder = lv_img_create(ui_PP_acBck);
    lv_img_set_src(ui_PP_acShieldBorder, &ui_img_final_shield_border_png);
    lv_obj_set_width(ui_PP_acShieldBorder, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_acShieldBorder, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_acShieldBorder, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_acShieldBorder, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PP_acShieldBorder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PP_acShieldBorder, 220);

    ui_PP_nameBck = lv_obj_create(ui_PP_Bck);
    lv_obj_set_width(ui_PP_nameBck, 290);
    lv_obj_set_height(ui_PP_nameBck, 34);
    lv_obj_set_x(ui_PP_nameBck, 0);
    lv_obj_set_y(ui_PP_nameBck, -63);
    lv_obj_set_align(ui_PP_nameBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_nameBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_nameBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_nameBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_name = lv_label_create(ui_PP_nameBck);
    lv_obj_set_width(ui_PP_name, 270);
    lv_obj_set_height(ui_PP_name, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_PP_name, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PP_name, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_PP_name, "Bharstynox Ironfist");
    lv_obj_set_style_text_align(ui_PP_name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_name, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_toScreen_Prev = lv_obj_create(ui_PP_Bck);
    lv_obj_set_width(ui_PP_toScreen_Prev, 58);
    lv_obj_set_height(ui_PP_toScreen_Prev, 25);
    lv_obj_set_x(ui_PP_toScreen_Prev, -115);
    lv_obj_set_y(ui_PP_toScreen_Prev, -100);
    lv_obj_set_align(ui_PP_toScreen_Prev, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_toScreen_Prev, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_toScreen_Prev, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_toScreen_Prev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_toScreen_Prev_txt = lv_label_create(ui_PP_toScreen_Prev);
    lv_obj_set_width(ui_PP_toScreen_Prev_txt, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PP_toScreen_Prev_txt, LV_SIZE_CONTENT);    /// 23
    lv_obj_set_align(ui_PP_toScreen_Prev_txt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PP_toScreen_Prev_txt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_PP_toScreen_Prev_txt, "H P");
    lv_obj_set_style_text_align(ui_PP_toScreen_Prev_txt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_toScreen_Prev_txt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_targetBtn = lv_obj_create(ui_PP_Bck);
    lv_obj_set_width(ui_PP_targetBtn, 58);
    lv_obj_set_height(ui_PP_targetBtn, 25);
    lv_obj_set_x(ui_PP_targetBtn, 115);
    lv_obj_set_y(ui_PP_targetBtn, -100);
    lv_obj_set_align(ui_PP_targetBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_targetBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_targetBtn, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_targetBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_targetBtnTxt = lv_label_create(ui_PP_targetBtn);
    lv_obj_set_width(ui_PP_targetBtnTxt, LV_SIZE_CONTENT);   /// 55
    lv_obj_set_height(ui_PP_targetBtnTxt, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_align(ui_PP_targetBtnTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PP_targetBtnTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_PP_targetBtnTxt, "Target");
    lv_obj_set_style_text_align(ui_PP_targetBtnTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_targetBtnTxt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_turnCountBck = lv_obj_create(ui_PP_Bck);
    lv_obj_set_width(ui_PP_turnCountBck, 156);
    lv_obj_set_height(ui_PP_turnCountBck, 25);
    lv_obj_set_x(ui_PP_turnCountBck, 0);
    lv_obj_set_y(ui_PP_turnCountBck, -100);
    lv_obj_set_align(ui_PP_turnCountBck, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_turnCountBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_turnCountBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_turnCountBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_turnCountTxt = lv_label_create(ui_PP_turnCountBck);
    lv_obj_set_width(ui_PP_turnCountTxt, LV_SIZE_CONTENT);   /// 136
    lv_obj_set_height(ui_PP_turnCountTxt, LV_SIZE_CONTENT);    /// 22
    lv_obj_set_x(ui_PP_turnCountTxt, -9);
    lv_obj_set_y(ui_PP_turnCountTxt, 0);
    lv_obj_set_align(ui_PP_turnCountTxt, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PP_turnCountTxt, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_PP_turnCountTxt, "     Player Profile");
    lv_obj_set_style_text_align(ui_PP_turnCountTxt, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_turnCountTxt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_turnCountNum = lv_label_create(ui_PP_turnCountBck);
    lv_obj_set_width(ui_PP_turnCountNum, 16);
    lv_obj_set_height(ui_PP_turnCountNum, 22);
    lv_obj_set_x(ui_PP_turnCountNum, 64);
    lv_obj_set_y(ui_PP_turnCountNum, 0);
    lv_obj_set_align(ui_PP_turnCountNum, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PP_turnCountNum, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_PP_turnCountNum, " ");
    lv_obj_set_style_text_align(ui_PP_turnCountNum, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_turnCountNum, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_numInput = lv_obj_create(ui_PP_Bck);
    lv_obj_set_width(ui_PP_numInput, 290);
    lv_obj_set_height(ui_PP_numInput, 195);
    lv_obj_set_x(ui_PP_numInput, 0);
    lv_obj_set_y(ui_PP_numInput, 10);
    lv_obj_set_align(ui_PP_numInput, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_PP_numInput, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PP_numInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_numInput, lv_color_hex(0x393839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_numInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_numKeyboard = lv_keyboard_create(ui_PP_numInput);
    lv_keyboard_set_mode(ui_PP_numKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_PP_numKeyboard, 283);
    lv_obj_set_height(ui_PP_numKeyboard, 120);
    lv_obj_set_x(ui_PP_numKeyboard, 0);
    lv_obj_set_y(ui_PP_numKeyboard, 11);
    lv_obj_set_align(ui_PP_numKeyboard, LV_ALIGN_BOTTOM_MID);

    lv_obj_set_style_bg_color(ui_PP_numKeyboard, lv_color_hex(0x393839), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_numKeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_PP_numTextArea = lv_textarea_create(ui_PP_numInput);
    lv_obj_set_width(ui_PP_numTextArea, 265);
    lv_obj_set_height(ui_PP_numTextArea, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PP_numTextArea, 0);
    lv_obj_set_y(ui_PP_numTextArea, -60);
    lv_obj_set_align(ui_PP_numTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PP_numTextArea, "Insert Damage Amount    ");
    lv_textarea_set_one_line(ui_PP_numTextArea, true);
    lv_obj_clear_flag(ui_PP_numTextArea,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_PP_numTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_numTextArea, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PP_numTextArea, lv_color_hex(0x393839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_numTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PP_numTextArea, lv_color_hex(0x808080), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_numTextArea, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PP_numTextArea, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_numTextArea, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_PP_numAcBck = lv_obj_create(ui_PP_numInput);
    lv_obj_set_width(ui_PP_numAcBck, 290);
    lv_obj_set_height(ui_PP_numAcBck, 195);
    lv_obj_set_align(ui_PP_numAcBck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PP_numAcBck, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PP_numAcBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_numAcBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_numAcBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_coverTxt = lv_label_create(ui_PP_numAcBck);
    lv_obj_set_width(ui_PP_coverTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_coverTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PP_coverTxt, -94);
    lv_obj_set_y(ui_PP_coverTxt, -81);
    lv_obj_set_align(ui_PP_coverTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_coverTxt, "Cover Select:");
    lv_obj_set_style_text_font(ui_PP_coverTxt, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_coverBtn_half = lv_obj_create(ui_PP_numAcBck);
    lv_obj_set_width(ui_PP_coverBtn_half, 58);
    lv_obj_set_height(ui_PP_coverBtn_half, 23);
    lv_obj_set_x(ui_PP_coverBtn_half, -16);
    lv_obj_set_y(ui_PP_coverBtn_half, -83);
    lv_obj_set_align(ui_PP_coverBtn_half, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_coverBtn_half, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_PP_coverBtn_half, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_coverBtn_half, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PP_coverBtn_half, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_PP_coverBtn_half, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_coverTxt_half = lv_label_create(ui_PP_coverBtn_half);
    lv_obj_set_width(ui_PP_coverTxt_half, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_coverTxt_half, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_coverTxt_half, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_coverTxt_half, "Half");
    lv_obj_set_style_text_color(ui_PP_coverTxt_half, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_coverTxt_half, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_coverTxt_half, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PP_coverTxt_half, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_PP_coverTxt_half, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_coverBtn_threeQuarters = lv_obj_create(ui_PP_numAcBck);
    lv_obj_set_width(ui_PP_coverBtn_threeQuarters, 58);
    lv_obj_set_height(ui_PP_coverBtn_threeQuarters, 23);
    lv_obj_set_x(ui_PP_coverBtn_threeQuarters, 45);
    lv_obj_set_y(ui_PP_coverBtn_threeQuarters, -83);
    lv_obj_set_align(ui_PP_coverBtn_threeQuarters, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_coverBtn_threeQuarters, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_PP_coverBtn_threeQuarters, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_coverBtn_threeQuarters, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PP_coverBtn_threeQuarters, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_PP_coverBtn_threeQuarters, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_coverTxt_threeQuarters = lv_label_create(ui_PP_coverBtn_threeQuarters);
    lv_obj_set_width(ui_PP_coverTxt_threeQuarters, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_coverTxt_threeQuarters, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_coverTxt_threeQuarters, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_coverTxt_threeQuarters, "3 / 4");
    lv_obj_set_style_text_color(ui_PP_coverTxt_threeQuarters, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_coverTxt_threeQuarters, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_coverTxt_threeQuarters, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PP_coverTxt_threeQuarters, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_PP_coverTxt_threeQuarters, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_coverBtn_full = lv_obj_create(ui_PP_numAcBck);
    lv_obj_set_width(ui_PP_coverBtn_full, 58);
    lv_obj_set_height(ui_PP_coverBtn_full, 23);
    lv_obj_set_x(ui_PP_coverBtn_full, 107);
    lv_obj_set_y(ui_PP_coverBtn_full, -83);
    lv_obj_set_align(ui_PP_coverBtn_full, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_coverBtn_full, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_PP_coverBtn_full, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_coverBtn_full, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PP_coverBtn_full, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_PP_coverBtn_full, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_coverTxt_full = lv_label_create(ui_PP_coverBtn_full);
    lv_obj_set_width(ui_PP_coverTxt_full, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_coverTxt_full, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_coverTxt_full, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_coverTxt_full, "Full");
    lv_obj_set_style_text_color(ui_PP_coverTxt_full, lv_color_hex(0x444444), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_coverTxt_full, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_coverTxt_full, &ui_font_Black_Chancery_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_PP_coverTxt_full, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_text_opa(ui_PP_coverTxt_full, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PP_acTextArea = lv_textarea_create(ui_PP_numAcBck);
    lv_obj_set_width(ui_PP_acTextArea, 282);
    lv_obj_set_height(ui_PP_acTextArea, LV_SIZE_CONTENT);    /// 38
    lv_obj_set_x(ui_PP_acTextArea, 0);
    lv_obj_set_y(ui_PP_acTextArea, -48);
    lv_obj_set_align(ui_PP_acTextArea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PP_acTextArea, "Insert AC    ");
    lv_textarea_set_one_line(ui_PP_acTextArea, true);
    lv_obj_clear_flag(ui_PP_acTextArea, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_PP_acTextArea, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PP_acTextArea, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PP_acTextArea, lv_color_hex(0x393839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_acTextArea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PP_acTextArea, lv_color_hex(0x808080), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_acTextArea, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_PP_acTextArea, lv_color_hex(0x808080), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PP_acTextArea, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    ui_PP_acKeyboard = lv_keyboard_create(ui_PP_numAcBck);
    lv_keyboard_set_mode(ui_PP_acKeyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_PP_acKeyboard, 283);
    lv_obj_set_height(ui_PP_acKeyboard, 120);
    lv_obj_set_x(ui_PP_acKeyboard, 0);
    lv_obj_set_y(ui_PP_acKeyboard, 11);
    lv_obj_set_align(ui_PP_acKeyboard, LV_ALIGN_BOTTOM_MID);

    lv_obj_set_style_bg_color(ui_PP_acKeyboard, lv_color_hex(0x393839), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_acKeyboard, 255, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_PP_numConfirmBtn = lv_obj_create(ui_PP_numInput);
    lv_obj_set_width(ui_PP_numConfirmBtn, 110);
    lv_obj_set_height(ui_PP_numConfirmBtn, 57);
    lv_obj_set_x(ui_PP_numConfirmBtn, 85);
    lv_obj_set_y(ui_PP_numConfirmBtn, lv_pct(3));
    lv_obj_set_align(ui_PP_numConfirmBtn, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PP_numConfirmBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PP_numConfirmBtn, lv_color_hex(0x393839), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PP_numConfirmBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PP_numConfirmTxt = lv_label_create(ui_PP_numConfirmBtn);
    lv_obj_set_width(ui_PP_numConfirmTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PP_numConfirmTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PP_numConfirmTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PP_numConfirmTxt, "Confirm");
    lv_obj_set_style_text_font(ui_PP_numConfirmTxt, &ui_font_Black_Chancery_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPP_condMoreBck = lv_obj_create(ui_PlayerProfile);
    lv_obj_set_width(ui_PPP_condMoreBck, 295);
    lv_obj_set_height(ui_PPP_condMoreBck, 144);
    lv_obj_set_x(ui_PPP_condMoreBck, 0);
    lv_obj_set_y(ui_PPP_condMoreBck, 36);
    lv_obj_set_align(ui_PPP_condMoreBck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PPP_condMoreBck, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PPP_condMoreBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PPP_condMoreBck, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PPP_condMoreBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPP_condMoreClose = lv_obj_create(ui_PPP_condMoreBck);
    lv_obj_set_width(ui_PPP_condMoreClose, 33);
    lv_obj_set_height(ui_PPP_condMoreClose, 33);
    lv_obj_set_x(ui_PPP_condMoreClose, 120);
    lv_obj_set_y(ui_PPP_condMoreClose, -45);
    lv_obj_set_align(ui_PPP_condMoreClose, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PPP_condMoreClose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PPP_condMoreTxt = lv_label_create(ui_PPP_condMoreClose);
    lv_obj_set_width(ui_PPP_condMoreTxt, LV_SIZE_CONTENT);   /// 270
    lv_obj_set_height(ui_PPP_condMoreTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPP_condMoreTxt, 2);
    lv_obj_set_y(ui_PPP_condMoreTxt, 2);
    lv_obj_set_align(ui_PPP_condMoreTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPP_condMoreTxt, "x");
    lv_obj_set_style_text_align(ui_PPP_condMoreTxt, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PPP_condMoreTxt, &ui_font_Black_Chancery_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPP_cond0 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond0, &ui_img_conditions_new_blinded_png);
    lv_obj_set_width(ui_PPP_cond0, LV_SIZE_CONTENT);   /// 35
    lv_obj_set_height(ui_PPP_cond0, LV_SIZE_CONTENT);    /// 34
    lv_obj_set_x(ui_PPP_cond0, -120);
    lv_obj_set_y(ui_PPP_cond0, -45);
    lv_obj_set_align(ui_PPP_cond0, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond0, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond0, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond0, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond0, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond1 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond1, &ui_img_conditions_new_charmed_png);
    lv_obj_set_width(ui_PPP_cond1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond1, -80);
    lv_obj_set_y(ui_PPP_cond1, -45);
    lv_obj_set_align(ui_PPP_cond1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond1, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond1, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond1, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond2 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond2, &ui_img_conditions_new_deafened_png);
    lv_obj_set_width(ui_PPP_cond2, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond2, -40);
    lv_obj_set_y(ui_PPP_cond2, -45);
    lv_obj_set_align(ui_PPP_cond2, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond2, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond2, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond2, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond3 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond3, &ui_img_conditionextra_new_disarmed_png);
    lv_obj_set_width(ui_PPP_cond3, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond3, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond3, 0);
    lv_obj_set_y(ui_PPP_cond3, -45);
    lv_obj_set_align(ui_PPP_cond3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond3, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond3, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond3, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond4 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond4, &ui_img_conditions_new_exhausion_png);
    lv_obj_set_width(ui_PPP_cond4, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond4, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond4, 40);
    lv_obj_set_y(ui_PPP_cond4, -45);
    lv_obj_set_align(ui_PPP_cond4, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond4, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond4, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond4, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_condExhaustionNumBck = lv_obj_create(ui_PPP_cond4);
    lv_obj_set_width(ui_PPP_condExhaustionNumBck, 10);
    lv_obj_set_height(ui_PPP_condExhaustionNumBck, 12);
    lv_obj_set_x(ui_PPP_condExhaustionNumBck, -9);
    lv_obj_set_y(ui_PPP_condExhaustionNumBck, -9);
    lv_obj_set_align(ui_PPP_condExhaustionNumBck, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PPP_condExhaustionNumBck, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PPP_condExhaustionNumBck, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PPP_condExhaustionNumBck, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PPP_condExhaustionNumBck, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PPP_condExhaustionNumBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PPP_condExhaustionNumBck, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PPP_condExhaustionNumBck, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PPP_condExhaustionNumBck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PPP_condExhaustionNumBck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PPP_condExhaustionNumBck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPP_condExhaustionNum = lv_label_create(ui_PPP_condExhaustionNumBck);
    lv_obj_set_width(ui_PPP_condExhaustionNum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPP_condExhaustionNum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PPP_condExhaustionNum, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PPP_condExhaustionNum, "2");
    lv_obj_set_style_text_color(ui_PPP_condExhaustionNum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PPP_condExhaustionNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PPP_condExhaustionNum, &ui_font_Black_Chancery_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PPP_cond5 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond5, &ui_img_conditions_new_frightened_png);
    lv_obj_set_width(ui_PPP_cond5, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond5, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond5, 80);
    lv_obj_set_y(ui_PPP_cond5, -45);
    lv_obj_set_align(ui_PPP_cond5, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond5, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond5, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond5, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond6 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond6, &ui_img_conditions_new_grappled_png);
    lv_obj_set_width(ui_PPP_cond6, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond6, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond6, -120);
    lv_obj_set_y(ui_PPP_cond6, 0);
    lv_obj_set_align(ui_PPP_cond6, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond6, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond6, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond6, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond7 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond7, &ui_img_conditionextra_new_hidden_png);
    lv_obj_set_width(ui_PPP_cond7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PPP_cond7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PPP_cond7, -80);
    lv_obj_set_y(ui_PPP_cond7, 0);
    lv_obj_set_align(ui_PPP_cond7, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond7, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond7, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond7, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond8 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond8, &ui_img_conditions_new_incapacitated_png);
    lv_obj_set_width(ui_PPP_cond8, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond8, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond8, -40);
    lv_obj_set_y(ui_PPP_cond8, 0);
    lv_obj_set_align(ui_PPP_cond8, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond8, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond8, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond8, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond9 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond9, &ui_img_conditions_new_invisible_png);
    lv_obj_set_width(ui_PPP_cond9, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond9, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_align(ui_PPP_cond9, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond9, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond9, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond9, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond10 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond10, &ui_img_conditionextra_new_obscured_png);
    lv_obj_set_width(ui_PPP_cond10, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond10, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond10, 40);
    lv_obj_set_y(ui_PPP_cond10, 0);
    lv_obj_set_align(ui_PPP_cond10, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond10, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond10, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond10, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond11 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond11, &ui_img_conditions_new_paralyzed_png);
    lv_obj_set_width(ui_PPP_cond11, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond11, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond11, 80);
    lv_obj_set_y(ui_PPP_cond11, 0);
    lv_obj_set_align(ui_PPP_cond11, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond11, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond11, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond11, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond12 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond12, &ui_img_conditions_new_petrified_png);
    lv_obj_set_width(ui_PPP_cond12, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond12, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond12, 120);
    lv_obj_set_y(ui_PPP_cond12, 0);
    lv_obj_set_align(ui_PPP_cond12, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond12, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond12, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond12, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond13 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond13, &ui_img_conditions_new_poisoned_png);
    lv_obj_set_width(ui_PPP_cond13, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond13, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond13, -120);
    lv_obj_set_y(ui_PPP_cond13, 45);
    lv_obj_set_align(ui_PPP_cond13, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond13, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond13, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond13, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond14 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond14, &ui_img_conditions_new_prone_png);
    lv_obj_set_width(ui_PPP_cond14, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond14, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond14, -80);
    lv_obj_set_y(ui_PPP_cond14, 45);
    lv_obj_set_align(ui_PPP_cond14, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond14, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond14, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond14, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond15 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond15, &ui_img_conditionextra_new_raging_png);
    lv_obj_set_width(ui_PPP_cond15, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond15, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond15, -40);
    lv_obj_set_y(ui_PPP_cond15, 45);
    lv_obj_set_align(ui_PPP_cond15, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond15, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond15, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond15, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond16 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond16, &ui_img_conditions_new_restrained_png);
    lv_obj_set_width(ui_PPP_cond16, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond16, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond16, 0);
    lv_obj_set_y(ui_PPP_cond16, 45);
    lv_obj_set_align(ui_PPP_cond16, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond16, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond16, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond16, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond17 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond17, &ui_img_conditionextra_new_surprised_png);
    lv_obj_set_width(ui_PPP_cond17, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond17, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond17, 40);
    lv_obj_set_y(ui_PPP_cond17, 45);
    lv_obj_set_align(ui_PPP_cond17, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond17, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond17, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond17, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond18 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond18, &ui_img_conditions_new_stunned_png);
    lv_obj_set_width(ui_PPP_cond18, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond18, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond18, 80);
    lv_obj_set_y(ui_PPP_cond18, 45);
    lv_obj_set_align(ui_PPP_cond18, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond18, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond18, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond18, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_PPP_cond19 = lv_img_create(ui_PPP_condMoreBck);
    lv_img_set_src(ui_PPP_cond19, &ui_img_conditions_new_unconcious_png);
    lv_obj_set_width(ui_PPP_cond19, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_PPP_cond19, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_PPP_cond19, 120);
    lv_obj_set_y(ui_PPP_cond19, 45);
    lv_obj_set_align(ui_PPP_cond19, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_PPP_cond19, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_PPP_cond19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PPP_cond19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PPP_cond19, 220);
    lv_obj_set_style_blend_mode(ui_PPP_cond19, LV_BLEND_MODE_SUBTRACTIVE, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_PP_cond0, ui_event_PP_cond0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_cond1, ui_event_PP_cond1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_cond2, ui_event_PP_cond2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_condExhaustionNumBck, ui_event_PP_condExhaustionNumBck, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_cond3, ui_event_PP_cond3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_cond4, ui_event_PP_cond4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_condNextBtn, ui_event_PP_condNextBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_condPrevBtn, ui_event_PP_condPrevBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_condMoreBtn, ui_event_PP_condMoreBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_profPicBck, ui_event_PP_profPicBck, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_hpBck, ui_event_PP_hpBck, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_acBck, ui_event_PP_acBck, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_toScreen_Prev, ui_event_PP_toScreen_Prev, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_targetBtn, ui_event_PP_targetBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_turnCountBck, ui_event_PP_turnCountBck, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_PP_numKeyboard, ui_PP_numTextArea);
    lv_obj_add_event_cb(ui_PP_coverBtn_half, ui_event_PP_coverBtn_half, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_coverBtn_threeQuarters, ui_event_PP_coverBtn_threeQuarters, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_coverBtn_full, ui_event_PP_coverBtn_full, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_PP_acKeyboard, ui_PP_acTextArea);
    lv_obj_add_event_cb(ui_PP_numConfirmBtn, ui_event_PP_numConfirmBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PP_Bck, ui_event_PP_Bck, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_condMoreClose, ui_event_PPP_condMoreClose, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond0, ui_event_PPP_cond0, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond1, ui_event_PPP_cond1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond2, ui_event_PPP_cond2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond3, ui_event_PPP_cond3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_condExhaustionNumBck, ui_event_PPP_condExhaustionNumBck, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond4, ui_event_PPP_cond4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond5, ui_event_PPP_cond5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond6, ui_event_PPP_cond6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond7, ui_event_PPP_cond7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond8, ui_event_PPP_cond8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond9, ui_event_PPP_cond9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond10, ui_event_PPP_cond10, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond11, ui_event_PPP_cond11, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond12, ui_event_PPP_cond12, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond13, ui_event_PPP_cond13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond14, ui_event_PPP_cond14, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond15, ui_event_PPP_cond15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond16, ui_event_PPP_cond16, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond17, ui_event_PPP_cond17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond18, ui_event_PPP_cond18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PPP_cond19, ui_event_PPP_cond19, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayerProfile, ui_event_PlayerProfile, LV_EVENT_ALL, NULL);

}
