// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: dndv_select

#include "../ui.h"

void ui_Ready_To_Start_Screen_screen_init(void)
{
    ui_Ready_To_Start_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Ready_To_Start_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Ready_To_Start_Screen, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Ready_To_Start_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Name_Label = lv_label_create(ui_Ready_To_Start_Screen);
    lv_obj_set_width(ui_Name_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Name_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Name_Label, LV_ALIGN_CENTER);

    ui_PC_Label = lv_label_create(ui_Ready_To_Start_Screen);
    lv_obj_set_width(ui_PC_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PC_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PC_Label, LV_ALIGN_CENTER);

    ui_Begin_Game_Button = lv_btn_create(ui_Ready_To_Start_Screen);
    lv_obj_set_width(ui_Begin_Game_Button, 315);
    lv_obj_set_height(ui_Begin_Game_Button, 106);
    lv_obj_set_x(ui_Begin_Game_Button, 487);
    lv_obj_set_y(ui_Begin_Game_Button, 743);
    lv_obj_set_align(ui_Begin_Game_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Begin_Game_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Begin_Game_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Begin_Game_Button, lv_color_hex(0x11E8A1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Begin_Game_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Begin_Game_Button, lv_color_hex(0x8AFE3F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Begin_Game_Button, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Begin_Game_Button, ui_event_Begin_Game_Button, LV_EVENT_ALL, NULL);

}
