// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: dndv_select

#include "../ui.h"

void ui_Select_GM_Screen_screen_init(void)
{
    ui_Select_GM_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Select_GM_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Select_GM_Screen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Select_GM_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Select_GM_Button = lv_btn_create(ui_Select_GM_Screen);
    lv_obj_set_width(ui_Select_GM_Button, 320);
    lv_obj_set_height(ui_Select_GM_Button, 50);
    lv_obj_set_x(ui_Select_GM_Button, 12);
    lv_obj_set_y(ui_Select_GM_Button, 94);
    lv_obj_set_align(ui_Select_GM_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Select_GM_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Select_GM_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Select_GM_Button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Select_GM_Button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Select_GM_Button, ui_event_Select_GM_Button, LV_EVENT_ALL, NULL);

}
