// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void BeginPlayerSelectScreens(lv_event_t * e);
void GmInfoBroadcastCall(lv_event_t * e);
void KickPlayerBeforeStart(lv_event_t * e);

void ReadyToPlay(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
