// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#include "../ui.h"

void ui_event_comp_OptionButton_OptionButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    lv_obj_t ** comp_OptionButton = lv_event_get_user_data(e);
    if(event_code == LV_EVENT_CLICKED) {
        BeginPlayerSelectScreens(e);
    }
}

// COMPONENT OptionButton

lv_obj_t * ui_OptionButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_OptionButton;
    cui_OptionButton = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_OptionButton, lv_pct(100));
    lv_obj_set_height(cui_OptionButton, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_OptionButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_OptionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_OptionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_OptionLabel;
    cui_OptionLabel = lv_label_create(cui_OptionButton);
    lv_obj_set_width(cui_OptionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_OptionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_OptionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_OptionLabel, "Default Text");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_OPTIONBUTTON_NUM);
    children[UI_COMP_OPTIONBUTTON_OPTIONBUTTON] = cui_OptionButton;
    children[UI_COMP_OPTIONBUTTON_OPTIONLABEL] = cui_OptionLabel;
    lv_obj_add_event_cb(cui_OptionButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_OptionButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_OptionButton, ui_event_comp_OptionButton_OptionButton, LV_EVENT_ALL, children);
    ui_comp_OptionButton_create_hook(cui_OptionButton);
    return cui_OptionButton;
}

