// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GMButtonsPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_GMButtonsPanel, lv_pct(100));
    lv_obj_set_height(ui_GMButtonsPanel, lv_pct(100));
    lv_obj_set_x(ui_GMButtonsPanel, -2);
    lv_obj_set_y(ui_GMButtonsPanel, 1);
    lv_obj_set_align(ui_GMButtonsPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_GMButtonsPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_GMButtonsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_GMButtonsPanel, LV_DIR_VER);

    ui_GMOptionButtonDefault = ui_OptionButton_create(ui_GMButtonsPanel);
    lv_obj_set_x(ui_GMOptionButtonDefault, 0);
    lv_obj_set_y(ui_GMOptionButtonDefault, 0);

    lv_label_set_text(ui_comp_get_child(ui_GMOptionButtonDefault, UI_COMP_OPTIONBUTTON_OPTIONLABEL), "Waiting for GMs...");

    ui_OptionButton2 = ui_OptionButton_create(ui_GMButtonsPanel);
    lv_obj_set_x(ui_OptionButton2, 0);
    lv_obj_set_y(ui_OptionButton2, 0);      //TODO: Add this stuff to the component itself

    lv_obj_add_event_cb(ui_OptionButton2, ui_event_OptionButton2_OptionButton, LV_EVENT_ALL, NULL);

}
