// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: dndv_select

#include "../ui.h"

void ui_Choose_PC_Screen_screen_init(void)
{
    ui_Choose_PC_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Choose_PC_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Choose_PC_Screen, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Choose_PC_Screen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Choose_PC_Button = lv_btn_create(ui_Choose_PC_Screen);
    lv_obj_set_width(ui_Choose_PC_Button, 185);
    lv_obj_set_height(ui_Choose_PC_Button, 50);
    lv_obj_set_x(ui_Choose_PC_Button, 442);
    lv_obj_set_y(ui_Choose_PC_Button, 535);
    lv_obj_set_align(ui_Choose_PC_Button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Choose_PC_Button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Choose_PC_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Choose_PC_Button, ui_event_Choose_PC_Button, LV_EVENT_ALL, NULL);

}
