// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: dndv_select

#include "../ui.h"

void ui_Input_Key_Screen_screen_init(void)
{
    ui_Input_Key_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Input_Key_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Input_Key_Keyboard = lv_keyboard_create(ui_Input_Key_Screen);
    lv_keyboard_set_mode(ui_Input_Key_Keyboard, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Input_Key_Keyboard, 316);
    lv_obj_set_height(ui_Input_Key_Keyboard, 145);
    lv_obj_set_x(ui_Input_Key_Keyboard, 0);
    lv_obj_set_y(ui_Input_Key_Keyboard, 47);
    lv_obj_set_align(ui_Input_Key_Keyboard, LV_ALIGN_CENTER);

    ui_Input_Key_Text_Area = lv_textarea_create(ui_Input_Key_Screen);
    lv_obj_set_width(ui_Input_Key_Text_Area, 314);
    lv_obj_set_height(ui_Input_Key_Text_Area, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Input_Key_Text_Area, 0);
    lv_obj_set_y(ui_Input_Key_Text_Area, -48);
    lv_obj_set_align(ui_Input_Key_Text_Area, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Input_Key_Text_Area, "Input Key...");
    lv_textarea_set_one_line(ui_Input_Key_Text_Area, true);

    lv_keyboard_set_textarea(ui_Input_Key_Keyboard, ui_Input_Key_Text_Area);
    lv_obj_add_event_cb(ui_Input_Key_Keyboard, ui_event_Input_Key_Keyboard, LV_EVENT_ALL, NULL);

}
