// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#include "ui.h"

void BeginPlayerSelectScreens(lv_event_t * e)
{
	// Your code here
}

void GmInfoBroadcastCall(lv_event_t * e)
{
	// Your code here
}

void KickPlayerBeforeStart(lv_event_t * e)
{
	// Your code here
}
