// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#include "../ui.h"

void ui_GmAwaitPlayersScreen_screen_init(void)
{
    ui_GmAwaitPlayersScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GmAwaitPlayersScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_GmAwaitPlayersScreen, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_GmAwaitPlayersScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_row(ui_GmAwaitPlayersScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_GmAwaitPlayersScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GmAwaitPlayersList = lv_obj_create(ui_GmAwaitPlayersScreen);
    lv_obj_set_width(ui_GmAwaitPlayersList, lv_pct(100));
    lv_obj_set_height(ui_GmAwaitPlayersList, lv_pct(80));
    lv_obj_set_x(ui_GmAwaitPlayersList, -284);
    lv_obj_set_y(ui_GmAwaitPlayersList, -95);
    lv_obj_set_align(ui_GmAwaitPlayersList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_GmAwaitPlayersList, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_GmAwaitPlayersList, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_GmAwaitPlayersList, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PlayerKickFirstPanel = ui_PlayerKickPanel_create(ui_GmAwaitPlayersList);
    lv_obj_set_x(ui_PlayerKickFirstPanel, 0);
    lv_obj_set_y(ui_PlayerKickFirstPanel, 0);

    ui_GmAwaitPlayersStartButton = lv_btn_create(ui_GmAwaitPlayersScreen);
    lv_obj_set_width(ui_GmAwaitPlayersStartButton, lv_pct(100));
    lv_obj_set_height(ui_GmAwaitPlayersStartButton, lv_pct(20));
    lv_obj_set_x(ui_GmAwaitPlayersStartButton, -3);
    lv_obj_set_y(ui_GmAwaitPlayersStartButton, -46);
    lv_obj_set_align(ui_GmAwaitPlayersStartButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_GmAwaitPlayersStartButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_GmAwaitPlayersStartButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
