// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: DnDeviceSync

#include "../ui.h"

void ui_SelectGMScreen_screen_init(void)
{
    ui_SelectGMScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SelectGMScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_GMButtonsPanel = lv_obj_create(ui_SelectGMScreen);
    lv_obj_set_width(ui_GMButtonsPanel, lv_pct(100));
    lv_obj_set_height(ui_GMButtonsPanel, lv_pct(100));
    lv_obj_set_align(ui_GMButtonsPanel, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_GMButtonsPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_GMButtonsPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_scroll_dir(ui_GMButtonsPanel, LV_DIR_VER);

    ui_BecomeGMOptionButton = lv_btn_create(ui_GMButtonsPanel);
    lv_obj_set_width(ui_BecomeGMOptionButton, lv_pct(100));
    lv_obj_set_height(ui_BecomeGMOptionButton, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_BecomeGMOptionButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BecomeGMOptionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BecomeGMOptionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BecomeGMOptionLabel = lv_label_create(ui_BecomeGMOptionButton);
    lv_obj_set_width(ui_BecomeGMOptionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BecomeGMOptionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BecomeGMOptionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BecomeGMOptionLabel, "Waiting for GMs...");

    ui_GMOptionFirstButton = ui_OptionButton_create(ui_GMButtonsPanel);
    lv_obj_set_x(ui_GMOptionFirstButton, 0);
    lv_obj_set_y(ui_GMOptionFirstButton, 0);

    lv_obj_add_event_cb(ui_BecomeGMOptionButton, ui_event_BecomeGMOptionButton, LV_EVENT_ALL, NULL);

}
