// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PlayerProfile_New

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void DmgMain_Animation(lv_obj_t * TargetObject, int delay);
void HealMain_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_HealthProfile
void ui_HealthProfile_screen_init(void);
lv_obj_t * ui_HealthProfile;
lv_obj_t * ui_HP_Bck;
lv_obj_t * ui_HP_hpBck;
lv_obj_t * ui_HP_hpFill;
lv_obj_t * ui_HP_hpTempFill;
lv_obj_t * ui_HP_hpReduceMax;
lv_obj_t * ui_HP_hpHeart;
void ui_event_HP_hpTotal(lv_event_t * e);
lv_obj_t * ui_HP_hpTotal;
void ui_event_HP_healBtn(lv_event_t * e);
lv_obj_t * ui_HP_healBtn;
lv_obj_t * ui_HP_healTxt;
lv_obj_t * ui_HP_title;
lv_obj_t * ui_HP_titleTxt;
void ui_event_HP_toScreen_PP(lv_event_t * e);
lv_obj_t * ui_HP_toScreen_PP;
lv_obj_t * ui_HP_profPic;
lv_obj_t * ui_HP_toScreen_XX;
lv_obj_t * ui_HP_hpMoreBck;
void ui_event_HP_hpMoreTemp(lv_event_t * e);
lv_obj_t * ui_HP_hpMoreTemp;
lv_obj_t * ui_HP_hpMoreTempTxt;
void ui_event_HP_hpMoreCurrent(lv_event_t * e);
lv_obj_t * ui_HP_hpMoreCurrent;
lv_obj_t * ui_HP_hpMoreCurrentTxt;
void ui_event_HP_hpMoreMax(lv_event_t * e);
lv_obj_t * ui_HP_hpMoreMax;
lv_obj_t * ui_HP_hpMoreMaxTxt;
lv_obj_t * ui_HP_healInput;
lv_obj_t * ui_HP_healKeyboard;
void ui_event_HP_healConfirmBtn(lv_event_t * e);
lv_obj_t * ui_HP_healConfirmBtn;
lv_obj_t * ui_HP_healConfirmTxt;
lv_obj_t * ui_HP_healTextArea;


// SCREEN: ui_PlayerProfile
void ui_PlayerProfile_screen_init(void);
lv_obj_t * ui_PlayerProfile;
void ui_event_PP_Bck(lv_event_t * e);
lv_obj_t * ui_PP_Bck;
lv_obj_t * ui_PP_condBck;
void ui_event_PP_condBlinded(lv_event_t * e);
lv_obj_t * ui_PP_condBlinded;
void ui_event_PP_condCharmed(lv_event_t * e);
lv_obj_t * ui_PP_condCharmed;
void ui_event_PP_condDeafened(lv_event_t * e);
lv_obj_t * ui_PP_condDeafened;
void ui_event_PP_condExhaustion(lv_event_t * e);
lv_obj_t * ui_PP_condExhaustion;
lv_obj_t * ui_PP_condExhaustionNumBck;
lv_obj_t * ui_PP_condExhaustionNum;
void ui_event_PP_condFrightened(lv_event_t * e);
lv_obj_t * ui_PP_condFrightened;
void ui_event_PP_condNextBtn(lv_event_t * e);
lv_obj_t * ui_PP_condNextBtn;
lv_obj_t * ui_PP_condNextTxt;
void ui_event_PP_condLastBtn(lv_event_t * e);
lv_obj_t * ui_PP_condLastBtn;
lv_obj_t * ui_PP_condLastTxt;
void ui_event_PP_condMoreBtn(lv_event_t * e);
lv_obj_t * ui_PP_condMoreBtn;
lv_obj_t * ui_PP_condMoreTxt;
lv_obj_t * ui_PP_profilePic;
lv_obj_t * ui_PP_profPicArtificer;
lv_obj_t * ui_PP_profPicWarlock;
lv_obj_t * ui_PP_profPicTWP;
lv_obj_t * ui_PP_hpBck;
lv_obj_t * ui_PP_hpFill;
lv_obj_t * ui_PP_hpTempFill;
lv_obj_t * ui_PP_hpReduceMax;
lv_obj_t * ui_PP_hpHeart;
lv_obj_t * ui_PP_hpTotal;
void ui_event_PP_acBck(lv_event_t * e);
lv_obj_t * ui_PP_acBck;
lv_obj_t * ui_PP_acCover_half;
lv_obj_t * ui_PP_acCover_threeQuarter;
lv_obj_t * ui_PP_acCover_total;
lv_obj_t * ui_PP_acShield;
lv_obj_t * ui_PP_acTotal;
lv_obj_t * ui_PP_acMath;
lv_obj_t * ui_PP_nameBck;
lv_obj_t * ui_PP_name;
void ui_event_PP_toScreen_Prev(lv_event_t * e);
lv_obj_t * ui_PP_toScreen_Prev;
lv_obj_t * ui_PP_toScreen_Prev_txt;
void ui_event_PP_targetBtn(lv_event_t * e);
lv_obj_t * ui_PP_targetBtn;
lv_obj_t * ui_PP_targetBtnTxt;
void ui_event_PP_turnCountBck(lv_event_t * e);
lv_obj_t * ui_PP_turnCountBck;
lv_obj_t * ui_PP_turnCountTxt;
lv_obj_t * ui_PP_turnCountNum;
lv_obj_t * ui_PP_dmgInput;
lv_obj_t * ui_PP_dmgKeyboard;
void ui_event_PP_dmgConfirmBtn(lv_event_t * e);
lv_obj_t * ui_PP_dmgConfirmBtn;
lv_obj_t * ui_PP_dmgConfirmTxt;
lv_obj_t * ui_PP_dmgTextArea;
lv_obj_t * ui_PP_acInput;
lv_obj_t * ui_PP_acKeyboard;
void ui_event_PP_acConfirmBtn(lv_event_t * e);
lv_obj_t * ui_PP_acConfirmBtn;
lv_obj_t * ui_PP_acConfirmTxt;
lv_obj_t * ui_PP_acTextArea;
lv_obj_t * ui_PPP_condMoreBck;
void ui_event_PPP_condMoreClose(lv_event_t * e);
lv_obj_t * ui_PPP_condMoreClose;
lv_obj_t * ui_PPP_condMoreTxt;
void ui_event_PPP_condBlinded(lv_event_t * e);
lv_obj_t * ui_PPP_condBlinded;
void ui_event_PPP_condCharmed(lv_event_t * e);
lv_obj_t * ui_PPP_condCharmed;
void ui_event_PPP_condDeafened(lv_event_t * e);
lv_obj_t * ui_PPP_condDeafened;
void ui_event_PPP_condDisarmed(lv_event_t * e);
lv_obj_t * ui_PPP_condDisarmed;
void ui_event_PPP_condExhaustion(lv_event_t * e);
lv_obj_t * ui_PPP_condExhaustion;
lv_obj_t * ui_PPP_condExhaustionNumBck;
lv_obj_t * ui_PPP_condExhaustionNum;
void ui_event_PPP_condFrightened(lv_event_t * e);
lv_obj_t * ui_PPP_condFrightened;
void ui_event_PPP_condGrappled(lv_event_t * e);
lv_obj_t * ui_PPP_condGrappled;
void ui_event_PPP_condHidden(lv_event_t * e);
lv_obj_t * ui_PPP_condHidden;
void ui_event_PPP_condIncapacitated(lv_event_t * e);
lv_obj_t * ui_PPP_condIncapacitated;
void ui_event_PPP_condInvisible(lv_event_t * e);
lv_obj_t * ui_PPP_condInvisible;
void ui_event_PPP_condObscured(lv_event_t * e);
lv_obj_t * ui_PPP_condObscured;
void ui_event_PPP_condParalyzed(lv_event_t * e);
lv_obj_t * ui_PPP_condParalyzed;
void ui_event_PPP_condPetrified(lv_event_t * e);
lv_obj_t * ui_PPP_condPetrified;
void ui_event_PPP_condPoisoned(lv_event_t * e);
lv_obj_t * ui_PPP_condPoisoned;
void ui_event_PPP_condProne(lv_event_t * e);
lv_obj_t * ui_PPP_condProne;
void ui_event_PPP_condRaging(lv_event_t * e);
lv_obj_t * ui_PPP_condRaging;
void ui_event_PPP_condRestained(lv_event_t * e);
lv_obj_t * ui_PPP_condRestained;
void ui_event_PPP_condSurprised(lv_event_t * e);
lv_obj_t * ui_PPP_condSurprised;
void ui_event_PPP_condStunned(lv_event_t * e);
lv_obj_t * ui_PPP_condStunned;
void ui_event_PPP_condUnconcious(lv_event_t * e);
lv_obj_t * ui_PPP_condUnconcious;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1488891476[1] = {&ui_img_539176514};
const lv_img_dsc_t * ui_imgset_1473017109[1] = {&ui_img_2136458485};
const lv_img_dsc_t * ui_imgset_1727690704[1] = {&ui_img_1631664762};
const lv_img_dsc_t * ui_imgset_114083553[1] = {&ui_img_241387375};
const lv_img_dsc_t * ui_imgset_362005569[1] = {&ui_img_2048466797};
const lv_img_dsc_t * ui_imgset_615561743[1] = {&ui_img_1701153993};
const lv_img_dsc_t * ui_imgset_1643377433[1] = {&ui_img_2075715036};
const lv_img_dsc_t * ui_imgset_d[2] = {&ui_img_images_d20_png, &ui_img_d20_png};
const lv_img_dsc_t * ui_imgset_d20pos[3] = {&ui_img_rollingdice_d20pos1_png, &ui_img_rollingdice_d20pos3_png, &ui_img_rollingdice_d20pos4_png};
const lv_img_dsc_t * ui_imgset_d0pos[1] = {&ui_img_rollingdice_d20pos2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if 0 //LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void DmgMain_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -8, 10);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 50);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, 10, -8);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 210);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}
void HealMain_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -8, -26);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 25);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, -26, -8);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 210);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_HP_hpTotal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        HealMain_Animation(ui_HP_hpTotal, 0);
        dndv_HP_healXdmg(e);
    }
}
void ui_event_HP_healBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_HP_healInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_HP_toScreen_PP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PlayerProfile, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_PlayerProfile_screen_init);
    }
}
void ui_event_HP_hpMoreTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        dndv_HP_modifyHpTemp(e);
    }
}
void ui_event_HP_hpMoreCurrent(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        dndv_HP_modifyHpCurrent(e);
    }
}
void ui_event_HP_hpMoreMax(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        dndv_HP_modifyHpMax(e);
    }
}
void ui_event_HP_healConfirmBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_HP_healInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_PP_Bck(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        dndv_PP_refresh(e);
    }
}
void ui_event_PP_condBlinded(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PP_condBlinded, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PP_condCharmed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PP_condCharmed, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PP_condDeafened(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PP_condDeafened, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PP_condExhaustion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PP_condExhaustion, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        _ui_flag_modify(ui_PP_condExhaustionNumBck, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PP_condFrightened(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PP_condFrightened, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PP_condNextBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        dndv_PP_condRight(e);
    }
}
void ui_event_PP_condLastBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        dndv_PP_condLeft(e);
    }
}
void ui_event_PP_condMoreBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PPP_condMoreBck, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        dndv_PP_condMore(e);
    }
}
void ui_event_PP_acBck(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PP_acInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_PP_toScreen_Prev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_HealthProfile, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_HealthProfile_screen_init);
    }
}
void ui_event_PP_targetBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PP_dmgInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_PP_turnCountBck(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        dndv_PP_InitScreen(e);
    }
}
void ui_event_PP_dmgConfirmBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PP_dmgInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_PP_acConfirmBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PP_acInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_PPP_condMoreClose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PPP_condMoreBck, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        dndv_PP_condMoreClose(e);
    }
}
void ui_event_PPP_condBlinded(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condBlinded, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condCharmed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condCharmed, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condDeafened(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condDeafened, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condDisarmed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condDisarmed, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condExhaustion(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condExhaustion, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        _ui_flag_modify(ui_PPP_condExhaustionNumBck, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}
void ui_event_PPP_condFrightened(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condFrightened, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condGrappled(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condGrappled, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condHidden(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condHidden, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condIncapacitated(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condIncapacitated, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condInvisible(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condInvisible, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condObscured(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condObscured, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condParalyzed(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condParalyzed, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condPetrified(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condPetrified, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condPoisoned(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condPoisoned, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condProne(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condProne, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condRaging(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condRaging, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condRestained(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condRestained, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condSurprised(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condSurprised, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condStunned(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condStunned, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_PPP_condUnconcious(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_PPP_condUnconcious, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HealthProfile_screen_init();
    ui_PlayerProfile_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HealthProfile);
}
