// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: dndv_select

#include "ui.h"
#include "ui_helpers.h"

#include "dndv_sync.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Select_GM_Screen
void ui_Select_GM_Screen_screen_init(void);
lv_obj_t * ui_Select_GM_Screen;
void ui_event_Select_GM_Button(lv_event_t * e);
lv_obj_t * ui_Select_GM_Button;

// SCREEN: ui_Input_Key_Screen
void ui_Input_Key_Screen_screen_init(void);
lv_obj_t * ui_Input_Key_Screen;
void ui_event_Input_Key_Keyboard(lv_event_t * e);
lv_obj_t * ui_Input_Key_Keyboard;
lv_obj_t * ui_Input_Key_Text_Area;

// SCREEN: ui_Choose_PC_Screen
void ui_Choose_PC_Screen_screen_init(void);
lv_obj_t * ui_Choose_PC_Screen;
void ui_event_Choose_PC_Button(lv_event_t * e);
lv_obj_t * ui_Choose_PC_Button;

// SCREEN: ui_Ready_To_Start_Screen
void ui_Ready_To_Start_Screen_screen_init(void);
lv_obj_t * ui_Ready_To_Start_Screen;
lv_obj_t * ui_Name_Label;
lv_obj_t * ui_PC_Label;
void ui_event_Begin_Game_Button(lv_event_t * e);
lv_obj_t * ui_Begin_Game_Button;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Select_GM_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(ui_Input_Key_Screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
    }
}
void ui_event_Input_Key_Keyboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_READY) { //This triggers when keyboard enter is pressed
        requestPlayer(1);
        _ui_screen_change(ui_Choose_PC_Screen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0);
    }
}
void ui_event_Choose_PC_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        requestPC(1);
        //TODO: Can I pause here while getting the data? Nah, refresh once the data is received
        _ui_screen_change(ui_Ready_To_Start_Screen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
    }
}
void ui_event_Begin_Game_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        ReadyToPlay(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Select_GM_Screen_screen_init();
    ui_Input_Key_Screen_screen_init();
    ui_Choose_PC_Screen_screen_init();
    ui_Ready_To_Start_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Select_GM_Screen);
}
