// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: DnDevice_HpSide_New

#include "ui.h"
#include "ui_helpers.h"

#include "screen_actions.h"

///////////////////// VARIABLES ////////////////////
void DamageMain_Animation(lv_obj_t * TargetObject, int delay);
void HealMain_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_hpInfoScrn

void ui_hpInfoScrn_screen_init();

void ui_event_hpInfoScrn(lv_event_t * e);
lv_obj_t * ui_hpInfoScrn;
lv_obj_t * ui_HP_Bck;
lv_obj_t * ui_HP_hpFill;
lv_obj_t * ui_HP_hpTempFill;
lv_obj_t * ui_HP_hpReduceMax;
lv_obj_t * ui_HP_hpHeart;
lv_obj_t * ui_HP_hpTotal;
lv_obj_t * ui_HP_HeartPic;
lv_obj_t * ui_HP_hpMax;
lv_obj_t * ui_HP_hpMaxTxt;
lv_obj_t * ui_HP_hpCurrent;
lv_obj_t * ui_HP_hpCurrentTxt;
lv_obj_t * ui_HP_hpTemp;
lv_obj_t * ui_HP_hpTempTxt;
void ui_event_HP_healBtn(lv_event_t * e);
lv_obj_t * ui_HP_healBtn;
lv_obj_t * ui_HP_healTxt;
lv_obj_t * ui_HP_titleBck;
lv_obj_t * ui_HP_title;
lv_obj_t * ui_HP_toScreen_MS;
lv_obj_t * ui_HP_toScreen_MS_pic;
lv_obj_t * ui_HP_toScreen_PP;
lv_obj_t * ui_profPicArtificer;
lv_obj_t * ui_profPicWarlock;
lv_obj_t * ui_HP_healInput;
lv_obj_t * ui_HP_healKeyboard;
lv_obj_t * ui_HP_healTextArea;
void ui_event_HP_healConfirmBtn(lv_event_t * e);
lv_obj_t * ui_HP_healConfirmBtn;
lv_obj_t * ui_HP_healConfirmTxt;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1488891476[1] = {&ui_img_539176514};
const lv_img_dsc_t * ui_imgset_1473017109[1] = {&ui_img_2136458485};
const lv_img_dsc_t * ui_imgset_1727690704[1] = {&ui_img_1631664762};
const lv_img_dsc_t * ui_imgset_114083553[1] = {&ui_img_241387375};
const lv_img_dsc_t * ui_imgset_362005569[1] = {&ui_img_2048466797};
const lv_img_dsc_t * ui_imgset_615561743[1] = {&ui_img_1701153993};
const lv_img_dsc_t * ui_imgset_1643377433[1] = {&ui_img_2075715036};
const lv_img_dsc_t * ui_imgset_d[2] = {&ui_img_images_d20_png, &ui_img_d20_png};
const lv_img_dsc_t * ui_imgset_d20pos[3] = {&ui_img_rollingdice_d20pos1_png, &ui_img_rollingdice_d20pos3_png, &ui_img_rollingdice_d20pos4_png};
const lv_img_dsc_t * ui_imgset_d0pos[1] = {&ui_img_rollingdice_d20pos2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if 0 // LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void DamageMain_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -8, 10);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 50);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, 10, -8);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 210);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}
void HealMain_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 100);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_0, -8, -26);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, true);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 25);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_y);
    lv_anim_set_values(&PropertyAnimation_1, -26, -8);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 110);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_hpInfoScrn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_slider_set_text_value(ui_HP_hpTotal, target, "", "");
    }
}
void ui_event_HP_healBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_HP_healInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_HP_healConfirmBtn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_HP_healInput, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        dndv_healPC(lv_textarea_get_text(ui_HP_healTextArea));
        lv_textarea_set_text(ui_HP_healTextArea, "");       //THIS IS ALSO CUSTOM   
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_hpInfoScrn_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_hpInfoScrn);

    dndv_refresh();
}