// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: Stage1_IS_HP_PP_PPP

#ifndef _STAGE1_IS_HP_PP_PPP_UI_H
#define _STAGE1_IS_HP_PP_PPP_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "screen_actions.h"

void DmgMain_Animation(lv_obj_t * TargetObject, int delay);
void HealMain_Animation(lv_obj_t * TargetObject, int delay);
void IntroDropIn_Animation(lv_obj_t * TargetObject, int delay);
void IntroRevealTxt_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_HealthProfile
void ui_HealthProfile_screen_init(void);
void ui_event_HealthProfile(lv_event_t * e);
extern lv_obj_t * ui_HealthProfile;
extern lv_obj_t * ui_HP_Bck;
extern lv_obj_t * ui_HP_hpBck;
extern lv_obj_t * ui_HP_hpMaxFill;
extern lv_obj_t * ui_HP_hpFill;
extern lv_obj_t * ui_HP_hpTempFill;
extern lv_obj_t * ui_HP_hpHeart;
void ui_event_HP_hpTotal(lv_event_t * e);
extern lv_obj_t * ui_HP_hpTotal;
extern lv_obj_t * ui_HP_hpHeartBorder;
void ui_event_HP_restLongBtn(lv_event_t * e);
extern lv_obj_t * ui_HP_restLongBtn;
extern lv_obj_t * ui_HP_restLongTxt;
void ui_event_HP_restShortBtn(lv_event_t * e);
extern lv_obj_t * ui_HP_restShortBtn;
extern lv_obj_t * ui_HP_restShortTxt;
extern lv_obj_t * ui_HP_title;
extern lv_obj_t * ui_HP_titleTxt;
void ui_event_HP_toScreen_PP(lv_event_t * e);
extern lv_obj_t * ui_HP_toScreen_PP;
extern lv_obj_t * ui_HP_profPic;
extern lv_obj_t * ui_HP_toScreen_XX;
extern lv_obj_t * ui_HP_hpMoreBck;
void ui_event_HP_hpMoreTemp(lv_event_t * e);
extern lv_obj_t * ui_HP_hpMoreTemp;
void ui_event_HP_hpMoreTempTxt(lv_event_t * e);
extern lv_obj_t * ui_HP_hpMoreTempTxt;
void ui_event_HP_hpMoreCurrent(lv_event_t * e);
extern lv_obj_t * ui_HP_hpMoreCurrent;
void ui_event_HP_hpMoreCurrentTxt(lv_event_t * e);
extern lv_obj_t * ui_HP_hpMoreCurrentTxt;
void ui_event_HP_hpMoreMax(lv_event_t * e);
extern lv_obj_t * ui_HP_hpMoreMax;
void ui_event_HP_hpMoreMaxTxt(lv_event_t * e);
extern lv_obj_t * ui_HP_hpMoreMaxTxt;
extern lv_obj_t * ui_HP_numInput;
extern lv_obj_t * ui_HP_numKeyboard;
void ui_event_HP_numConfirmBtn(lv_event_t * e);
extern lv_obj_t * ui_HP_numConfirmBtn;
extern lv_obj_t * ui_HP_numConfirmTxt;
extern lv_obj_t * ui_HP_numTextArea;
// SCREEN: ui_PlayerProfile
void ui_PlayerProfile_screen_init(void);
void ui_event_PlayerProfile(lv_event_t * e);
extern lv_obj_t * ui_PlayerProfile;
void ui_event_PP_Bck(lv_event_t * e);
extern lv_obj_t * ui_PP_Bck;
extern lv_obj_t * ui_PP_condBck;
void ui_event_PP_cond0(lv_event_t * e);
extern lv_obj_t * ui_PP_cond0;
void ui_event_PP_cond1(lv_event_t * e);
extern lv_obj_t * ui_PP_cond1;
void ui_event_PP_cond2(lv_event_t * e);
extern lv_obj_t * ui_PP_cond2;
void ui_event_PP_cond3(lv_event_t * e);
extern lv_obj_t * ui_PP_cond3;
void ui_event_PP_cond4(lv_event_t * e);
extern lv_obj_t * ui_PP_cond4;
void ui_event_PP_condExhaustionNumBck(lv_event_t * e);
extern lv_obj_t * ui_PP_condExhaustionNumBck;
extern lv_obj_t * ui_PP_condExhaustionNum;
void ui_event_PP_condNextBtn(lv_event_t * e);
extern lv_obj_t * ui_PP_condNextBtn;
extern lv_obj_t * ui_PP_condNextTxt;
void ui_event_PP_condPrevBtn(lv_event_t * e);
extern lv_obj_t * ui_PP_condPrevBtn;
extern lv_obj_t * ui_PP_condPrevTxt;
void ui_event_PP_condMoreBtn(lv_event_t * e);
extern lv_obj_t * ui_PP_condMoreBtn;
extern lv_obj_t * ui_PP_condMoreTxt;
void ui_event_PP_profPicBck(lv_event_t * e);
extern lv_obj_t * ui_PP_profPicBck;
extern lv_obj_t * ui_PP_profPic;
void ui_event_PP_hpBck(lv_event_t * e);
extern lv_obj_t * ui_PP_hpBck;
extern lv_obj_t * ui_PP_hpMaxFill;
extern lv_obj_t * ui_PP_hpFill;
extern lv_obj_t * ui_PP_hpTempFill;
extern lv_obj_t * ui_PP_hpHeart;
extern lv_obj_t * ui_PP_hpTotal;
extern lv_obj_t * ui_PP_hpHeartBorder;
void ui_event_PP_acBck(lv_event_t * e);
extern lv_obj_t * ui_PP_acBck;
extern lv_obj_t * ui_PP_acCover_half;
extern lv_obj_t * ui_PP_acCover_threeQuarter;
extern lv_obj_t * ui_PP_acCover_total;
extern lv_obj_t * ui_PP_acShield;
extern lv_obj_t * ui_PP_acTotal;
extern lv_obj_t * ui_PP_acMath;
extern lv_obj_t * ui_PP_acShieldBorder;
extern lv_obj_t * ui_PP_nameBck;
extern lv_obj_t * ui_PP_name;
void ui_event_PP_toScreen_Prev(lv_event_t * e);
extern lv_obj_t * ui_PP_toScreen_Prev;
extern lv_obj_t * ui_PP_toScreen_Prev_txt;
void ui_event_PP_targetBtn(lv_event_t * e);
extern lv_obj_t * ui_PP_targetBtn;
extern lv_obj_t * ui_PP_targetBtnTxt;
void ui_event_PP_turnCountBck(lv_event_t * e);
extern lv_obj_t * ui_PP_turnCountBck;
extern lv_obj_t * ui_PP_turnCountTxt;
extern lv_obj_t * ui_PP_turnCountNum;
extern lv_obj_t * ui_PP_numInput;
extern lv_obj_t * ui_PP_numKeyboard;
extern lv_obj_t * ui_PP_numTextArea;
extern lv_obj_t * ui_PP_numAcBck;
extern lv_obj_t * ui_PP_coverTxt;
void ui_event_PP_coverBtn_half(lv_event_t * e);
extern lv_obj_t * ui_PP_coverBtn_half;
extern lv_obj_t * ui_PP_coverTxt_half;
void ui_event_PP_coverBtn_threeQuarters(lv_event_t * e);
extern lv_obj_t * ui_PP_coverBtn_threeQuarters;
extern lv_obj_t * ui_PP_coverTxt_threeQuarters;
void ui_event_PP_coverBtn_full(lv_event_t * e);
extern lv_obj_t * ui_PP_coverBtn_full;
extern lv_obj_t * ui_PP_coverTxt_full;
extern lv_obj_t * ui_PP_acTextArea;
extern lv_obj_t * ui_PP_acKeyboard;
void ui_event_PP_numConfirmBtn(lv_event_t * e);
extern lv_obj_t * ui_PP_numConfirmBtn;
extern lv_obj_t * ui_PP_numConfirmTxt;
extern lv_obj_t * ui_PPP_condMoreBck;
void ui_event_PPP_condMoreClose(lv_event_t * e);
extern lv_obj_t * ui_PPP_condMoreClose;
extern lv_obj_t * ui_PPP_condMoreTxt;
void ui_event_PPP_cond0(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond0;
void ui_event_PPP_cond1(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond1;
void ui_event_PPP_cond2(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond2;
void ui_event_PPP_cond3(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond3;
void ui_event_PPP_cond4(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond4;
void ui_event_PPP_cond5(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond5;
void ui_event_PPP_cond6(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond6;
void ui_event_PPP_cond7(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond7;
void ui_event_PPP_cond8(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond8;
void ui_event_PPP_cond9(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond9;
void ui_event_PPP_cond10(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond10;
void ui_event_PPP_cond11(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond11;
void ui_event_PPP_cond12(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond12;
void ui_event_PPP_cond13(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond13;
void ui_event_PPP_cond14(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond14;
void ui_event_PPP_cond15(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond15;
void ui_event_PPP_cond16(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond16;
void ui_event_PPP_cond17(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond17;
void ui_event_PPP_cond18(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond18;
void ui_event_PPP_cond19(lv_event_t * e);
extern lv_obj_t * ui_PPP_cond19;
void ui_event_PPP_condExhaustionNumBck(lv_event_t * e);
extern lv_obj_t * ui_PPP_condExhaustionNumBck;
extern lv_obj_t * ui_PPP_condExhaustionNum;
// SCREEN: ui_IntroScreen
void ui_IntroScreen_screen_init(void);
void ui_event_IntroScreen(lv_event_t * e);
extern lv_obj_t * ui_IntroScreen;
void ui_event_IS_Bck(lv_event_t * e);
extern lv_obj_t * ui_IS_Bck;
extern lv_obj_t * ui_IS_introText_D1;
extern lv_obj_t * ui_IS_introText_N1;
extern lv_obj_t * ui_IS_introText_D2;
extern lv_obj_t * ui_IS_introText_E1;
extern lv_obj_t * ui_IS_introText_V1;
extern lv_obj_t * ui_IS_introText_I1;
extern lv_obj_t * ui_IS_introText_C1;
extern lv_obj_t * ui_IS_introText_E2;
extern lv_obj_t * ui_IS_continueTxt;
// SCREEN: ui_PlayerCreation
void ui_PlayerCreation_screen_init(void);
void ui_event_PlayerCreation(lv_event_t * e);
extern lv_obj_t * ui_PlayerCreation;
extern lv_obj_t * ui_PC_Bck;
extern lv_obj_t * ui_PC_profPic;
void ui_event_PC_pfpNextBtn(lv_event_t * e);
extern lv_obj_t * ui_PC_pfpNextBtn;
extern lv_obj_t * ui_PC_pfpNextTxt;
void ui_event_PC_pfpPrevBtn(lv_event_t * e);
extern lv_obj_t * ui_PC_pfpPrevBtn;
extern lv_obj_t * ui_PC_pfpPrevTxt;
void ui_event_PC_confirmBck(lv_event_t * e);
extern lv_obj_t * ui_PC_confirmBck;
extern lv_obj_t * ui_PC_confirmTxt;
extern lv_obj_t * ui_PC_Input;
void ui_event_PC_InputKeyboard(lv_event_t * e);
extern lv_obj_t * ui_PC_InputKeyboard;
void ui_event_PC_InputConfirmBtn(lv_event_t * e);
extern lv_obj_t * ui_PC_InputConfirmBtn;
extern lv_obj_t * ui_PC_InputTextArea;
extern lv_obj_t * ui_PC_numInput;
extern lv_obj_t * ui_PC_numKeyboard;
void ui_event_PC_numConfirmBtn(lv_event_t * e);
extern lv_obj_t * ui_PC_numConfirmBtn;
extern lv_obj_t * ui_HP_numConfirmTxt2;
extern lv_obj_t * ui_PC_numTextArea;
void ui_event_PC_nameTxt(lv_event_t * e);
extern lv_obj_t * ui_PC_nameTxt;
void ui_event_PC_hpTxt(lv_event_t * e);
extern lv_obj_t * ui_PC_hpTxt;
void ui_event_PC_hpLabel(lv_event_t * e);
extern lv_obj_t * ui_PC_hpLabel;
void ui_event_PC_acTxt(lv_event_t * e);
extern lv_obj_t * ui_PC_acTxt;
void ui_event_PC_acLabel(lv_event_t * e);
extern lv_obj_t * ui_PC_acLabel;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_final_heart_png);    // assets/final_Heart.png
LV_IMG_DECLARE(ui_img_final_heart_border_png);    // assets/final_Heart_Border.png
LV_IMG_DECLARE(ui_img_playericons_icon_warlock_png);    // assets/PlayerIcons/Icon_Warlock.png
LV_IMG_DECLARE(ui_img_conditions_new_blinded_png);    // assets/Conditions/new_Blinded.png
LV_IMG_DECLARE(ui_img_conditions_new_charmed_png);    // assets/Conditions/new_Charmed.png
LV_IMG_DECLARE(ui_img_conditions_new_deafened_png);    // assets/Conditions/new_Deafened.png
LV_IMG_DECLARE(ui_img_conditions_new_exhausion_png);    // assets/Conditions/new_Exhausion.png
LV_IMG_DECLARE(ui_img_conditions_new_frightened_png);    // assets/Conditions/new_Frightened.png
LV_IMG_DECLARE(ui_img_conditionextra_cover_half_png);    // assets/ConditionExtra/Cover_half.png
LV_IMG_DECLARE(ui_img_conditionextra_cover_threequarter_png);    // assets/ConditionExtra/Cover_threeQuarter.png
LV_IMG_DECLARE(ui_img_conditionextra_cover_total_png);    // assets/ConditionExtra/Cover_total.png
LV_IMG_DECLARE(ui_img_final_shield_png);    // assets/final_Shield.png
LV_IMG_DECLARE(ui_img_final_shield_border_png);    // assets/final_Shield_Border.png
LV_IMG_DECLARE(ui_img_conditionextra_new_disarmed_png);    // assets/ConditionExtra/new_Disarmed.png
LV_IMG_DECLARE(ui_img_conditions_new_grappled_png);    // assets/Conditions/new_Grappled.png
LV_IMG_DECLARE(ui_img_conditionextra_new_hidden_png);    // assets/ConditionExtra/new_Hidden.png
LV_IMG_DECLARE(ui_img_conditions_new_incapacitated_png);    // assets/Conditions/new_Incapacitated.png
LV_IMG_DECLARE(ui_img_conditions_new_invisible_png);    // assets/Conditions/new_Invisible.png
LV_IMG_DECLARE(ui_img_conditionextra_new_obscured_png);    // assets/ConditionExtra/new_Obscured.png
LV_IMG_DECLARE(ui_img_conditions_new_paralyzed_png);    // assets/Conditions/new_Paralyzed.png
LV_IMG_DECLARE(ui_img_conditions_new_petrified_png);    // assets/Conditions/new_Petrified.png
LV_IMG_DECLARE(ui_img_conditions_new_poisoned_png);    // assets/Conditions/new_Poisoned.png
LV_IMG_DECLARE(ui_img_conditions_new_prone_png);    // assets/Conditions/new_Prone.png
LV_IMG_DECLARE(ui_img_conditionextra_new_raging_png);    // assets/ConditionExtra/new_Raging.png
LV_IMG_DECLARE(ui_img_conditions_new_restrained_png);    // assets/Conditions/new_Restrained.png
LV_IMG_DECLARE(ui_img_conditionextra_new_surprised_png);    // assets/ConditionExtra/new_Surprised.png
LV_IMG_DECLARE(ui_img_conditions_new_stunned_png);    // assets/Conditions/new_Stunned.png
LV_IMG_DECLARE(ui_img_conditions_new_unconcious_png);    // assets/Conditions/new_Unconcious.png
LV_IMG_DECLARE(ui_img_images_d20_png);    // assets/Images/d20.png


LV_IMG_DECLARE(ui_img_playericons_icon_artificer_png);
LV_IMG_DECLARE(ui_img_playericons_icon_barbarian_png);
LV_IMG_DECLARE(ui_img_playericons_icon_bard_png);
LV_IMG_DECLARE(ui_img_playericons_icon_cleric_png);
LV_IMG_DECLARE(ui_img_playericons_icon_druid_png);
LV_IMG_DECLARE(ui_img_playericons_icon_fighter_png);
LV_IMG_DECLARE(ui_img_playericons_icon_monk_png);
LV_IMG_DECLARE(ui_img_playericons_icon_paladin_png);
LV_IMG_DECLARE(ui_img_playericons_icon_ranger_png);
LV_IMG_DECLARE(ui_img_playericons_icon_rogue_png);
LV_IMG_DECLARE(ui_img_playericons_icon_sorcerer_png);
//LV_IMG_DECLARs\ui_img_playericons_icon_warlock_png);
LV_IMG_DECLARE(ui_img_playericons_icon_wizard_png);

LV_FONT_DECLARE(ui_font_Black_Chancery_14);
LV_FONT_DECLARE(ui_font_Black_Chancery_16);
LV_FONT_DECLARE(ui_font_Black_Chancery_20);
LV_FONT_DECLARE(ui_font_Black_Chancery_25);
LV_FONT_DECLARE(ui_font_Black_Chancery_30);
LV_FONT_DECLARE(ui_font_Black_Chancery_50);
LV_FONT_DECLARE(ui_font_Dungeon_50);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
