// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: DnDevice_HpSide_New

#ifndef _DNDEVICE_HPSIDE_NEW_UI_H
#define _DNDEVICE_HPSIDE_NEW_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void DamageMain_Animation(lv_obj_t * TargetObject, int delay);
void HealMain_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_hpInfoScrn
void ui_hpInfoScrn_screen_init(void);
void ui_event_hpInfoScrn(lv_event_t * e);
extern lv_obj_t * ui_hpInfoScrn;
extern lv_obj_t * ui_HP_Bck;
extern lv_obj_t * ui_HP_hpFill;
extern lv_obj_t * ui_HP_hpTempFill;
extern lv_obj_t * ui_HP_hpReduceMax;
extern lv_obj_t * ui_HP_hpHeart;
extern lv_obj_t * ui_HP_hpTotal;
extern lv_obj_t * ui_HP_HeartPic;
extern lv_obj_t * ui_HP_hpMax;
extern lv_obj_t * ui_HP_hpMaxTxt;
extern lv_obj_t * ui_HP_hpCurrent;
extern lv_obj_t * ui_HP_hpCurrentTxt;
extern lv_obj_t * ui_HP_hpTemp;
extern lv_obj_t * ui_HP_hpTempTxt;
void ui_event_HP_healBtn(lv_event_t * e);
extern lv_obj_t * ui_HP_healBtn;
extern lv_obj_t * ui_HP_healTxt;
extern lv_obj_t * ui_HP_titleBck;
extern lv_obj_t * ui_HP_title;
extern lv_obj_t * ui_HP_toScreen_MS;
extern lv_obj_t * ui_HP_toScreen_MS_pic;
extern lv_obj_t * ui_HP_toScreen_PP;
extern lv_obj_t * ui_profPicArtificer;
extern lv_obj_t * ui_profPicWarlock;
extern lv_obj_t * ui_HP_healInput;
extern lv_obj_t * ui_HP_healKeyboard;
extern lv_obj_t * ui_HP_healTextArea;
void ui_event_HP_healConfirmBtn(lv_event_t * e);
extern lv_obj_t * ui_HP_healConfirmBtn;
extern lv_obj_t * ui_HP_healConfirmTxt;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_851249624);    // assets\Images\Heart Outline - small.png
LV_IMG_DECLARE(ui_img_552092932);    // assets\Heart Outline - small.png
LV_IMG_DECLARE(ui_img_smallhomebtn_png);    // assets\SmallHomeBtn.png
LV_IMG_DECLARE(ui_img_playericons_icon_artificer_png);    // assets\PlayerIcons\Icon_Artificer.png
LV_IMG_DECLARE(ui_img_playericons_icon_warlock_png);    // assets\PlayerIcons\Icon_Warlock.png
LV_IMG_DECLARE(ui_img_539176514);    // assets\Conditions\10 - sMxDao4.png
LV_IMG_DECLARE(ui_img_2136458485);    // assets\Conditions\14 - gCB3xt0.png
LV_IMG_DECLARE(ui_img_1631664762);    // assets\Conditions\15 - Tcp83T3.png
LV_IMG_DECLARE(ui_img_241387375);    // assets\Conditions\2 - m9J6r00.png
LV_IMG_DECLARE(ui_img_2048466797);    // assets\Conditions\6 - ARfzri8.png
LV_IMG_DECLARE(ui_img_1701153993);    // assets\DamageTypes\12 - IagDlE1.png
LV_IMG_DECLARE(ui_img_2075715036);    // assets\DamageTypes\7 - IIztde9.png
LV_IMG_DECLARE(ui_img_images_d20_png);    // assets\Images\d20.png
LV_IMG_DECLARE(ui_img_rollingdice_d20pos1_png);    // assets\RollingDice\d20pos1.png
LV_IMG_DECLARE(ui_img_rollingdice_d20pos2_png);    // assets\RollingDice\d20pos2.png
LV_IMG_DECLARE(ui_img_rollingdice_d20pos3_png);    // assets\RollingDice\d20pos3.png
LV_IMG_DECLARE(ui_img_rollingdice_d20pos4_png);    // assets\RollingDice\d20pos4.png
LV_IMG_DECLARE(ui_img_d20_png);    // assets\d20.png

LV_FONT_DECLARE(ui_font_Aniron_50);
LV_FONT_DECLARE(ui_font_Aniron_Bold_50);
LV_FONT_DECLARE(ui_font_Black_Chancery_14);
LV_FONT_DECLARE(ui_font_Black_Chancery_16);
LV_FONT_DECLARE(ui_font_Black_Chancery_20);
LV_FONT_DECLARE(ui_font_Black_Chancery_25);
LV_FONT_DECLARE(ui_font_Black_Chancery_30);
LV_FONT_DECLARE(ui_font_Black_Chancery_50);
LV_FONT_DECLARE(ui_font_Draconis_50);
LV_FONT_DECLARE(ui_font_Draconis_Bold_50);
LV_FONT_DECLARE(ui_font_Draconis_Bold_Italics_50);
LV_FONT_DECLARE(ui_font_Draconis_Italics_50);
LV_FONT_DECLARE(ui_font_Dragon_Force_50);
LV_FONT_DECLARE(ui_font_Dragonwick_50);
LV_FONT_DECLARE(ui_font_Dungeon_50);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
