// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: PlayerProfile_New

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void dndv_HP_healXdmg(lv_event_t * e);
void dndv_HP_modifyHpTemp(lv_event_t * e);
void dndv_HP_modifyHpCurrent(lv_event_t * e);
void dndv_HP_modifyHpMax(lv_event_t * e);
void dndv_PP_refresh(lv_event_t * e);
void dndv_PP_condRight(lv_event_t * e);
void dndv_PP_condLeft(lv_event_t * e);
void dndv_PP_condMore(lv_event_t * e);
void dndv_PP_InitScreen(lv_event_t * e);
void dndv_PP_condMoreClose(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
